<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:28:06 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_portal_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['articles'] = array('authorIsMember','authorIsOnline','authorMemberLink','entryLastPoster','entryHasPosts','articles');
$this->_funcHooks['latestPosts'] = array('ismember','posts');
$this->_funcHooks['siteNavigation'] = array('links');
$this->_funcHooks['skeletonTemplate'] = array('disablelightbox');


}

/* -- affiliates --*/
function affiliates($links="") {
$IPBHTML = "";
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['aff_title']}</h3>
	<div class='inner_portal_box'>
		{$this->settings['csite_fav_contents']}
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- articles --*/
function articles($articles) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['articles'] ) )
{
$count_909286b4d498f0172195dd9d1d072414 = is_array($this->functionData['articles']) ? count($this->functionData['articles']) : 0;
$this->functionData['articles'][$count_909286b4d498f0172195dd9d1d072414]['articles'] = $articles;
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("topic", "0" ) . "".$this->__f__55ed2204514c8b231338d95091238282($articles)."";
return $IPBHTML;
}


function __f__55ed2204514c8b231338d95091238282($articles)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $articles as $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<h2 class='maintitle'><a style=\"text-decoration:none\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$entry['tid']}", "public",'' ), "{$entry['title_seo']}", "showtopic" ) . "'>{$entry['title']}</a></h2>
	<div class='generic_bar'></div>
	<div class='post_block first hentry no_sidebar' id='announce_id_{$announce['announce_id']}'>
		<div class='post_wrap'>
			" . (($entry['member_id']) ? ("
				<h3>
			") : ("
				<h3 class='guest'>
			")) . "
					" . (($entry['member_id']) ? ("" . (($entry['_online']) ? ("
							" . $this->registry->getClass('output')->getReplacement("user_online") . "
						") : ("
							" . $this->registry->getClass('output')->getReplacement("user_offline") . "
						")) . " &nbsp;
								<address class=\"author vcard\"><a class=\"url fn\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$entry['member_id']}", "public",'' ), "{$entry['members_seo_name']}", "showuser" ) . "'>{$entry['members_display_name']}</a>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($entry['member_id']) : '' ) . "</address>") : ("
						{$entry['members_display_name']}
					")) . "
					 - {$entry['date']} - " . $this->registry->getClass('class_localization')->formatNumber( $entry['posts'] ) . " {$this->lang->words['comments_suffix']}
				</h3>
			<div class='post_body'>
				<div class='post entry-content'>
					{$entry['post']}
					<!--IBF.ATTACHMENT_{$entry['pid']}-->
				</div>
			</div>
			<div class='moderation_bar'>
				" . (($entry['posts']) ? ("{$this->lang->words['read']} " . $this->registry->getClass('class_localization')->formatNumber( $entry['views'] ) . " {$this->lang->words['times_last']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$entry['tid']}&amp;view=getlastpost", "public",'' ), "{$entry['title_seo']}", "showtopic" ) . "'>{$this->lang->words['article_comment']}</a> {$this->lang->words['portal_by']} " . (($entry['last_poster_id']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$entry['last_poster_id']}", "public",'' ), "{$entry['seo_last_name']}", "showuser" ) . "'>{$entry['last_poster_name']}</a>") : ("{$entry['last_poster_name']}")) . "") : ("
					{$this->lang->words['read']} " . $this->registry->getClass('class_localization')->formatNumber( $entry['views'] ) . " {$this->lang->words['times_make']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$entry['tid']}&amp;view=getlastpost", "public",'' ), "{$entry['title_seo']}", "showtopic" ) . "'>{$this->lang->words['article_comment']}</a>
				")) . "
				{$bottom_string}
				&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=printtopic&amp;client=printer&amp;f={$entry['forum_id']}&amp;t={$entry['tid']}", "public",'' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("print_icon") . "</a>&nbsp;&nbsp;
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=forward&amp;f={$entry['forum_id']}&amp;t={$entry['tid']}", "public",'' ), "", "" ) . "'>" . $this->registry->getClass('output')->getReplacement("email_icon") . "</a>
			</div>
		</div>			
	</div>
	<br />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- calendarWrap --*/
function calendarWrap($content="") {
$IPBHTML = "";
$IPBHTML .= "{$content}
<br />";
return $IPBHTML;
}

/* -- latestPosts --*/
function latestPosts($posts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['latestPosts'] ) )
{
$count_44b55e4417c59b0228ff39897d60f79f = is_array($this->functionData['latestPosts']) ? count($this->functionData['latestPosts']) : 0;
$this->functionData['latestPosts'][$count_44b55e4417c59b0228ff39897d60f79f]['posts'] = $posts;
}

if ( ! isset( $this->registry->templateStriping['recent_topics'] ) ) {
$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['discuss_title']}</h3>
	<ul class='hfeed block_list'>
				".$this->__f__40d6ad6393c23adf857eaf16b2dcef98($posts)."	</ul>
</div>
<br />";
return $IPBHTML;
}


function __f__40d6ad6393c23adf857eaf16b2dcef98($posts=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $posts as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$result['tid']}", "public",'' ), "{$result['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$result['title']}</a> {$this->lang->words['portal_by']} <address class=\"author vcard\">" . (($result['member_id']) ? ("<a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$result['member_id']}", "public",'' ), "{$result['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$result['members_display_name']}</a>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($result['member_id']) : '' ) . "") : ("{$result['members_display_name']}")) . "</address> <span class='date'><abbr class=\"published\" title=\"" . date( 'c', $result['start_date'] ) . "\">(" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($result['start_date'],"short", 0)) . ")</abbr></span>
			<br />{$this->lang->words['recent_read']}: " . $this->registry->getClass('class_localization')->formatNumber( $result['views'] ) . " &nbsp; {$this->lang->words['recent_comments']}: " . $this->registry->getClass('class_localization')->formatNumber( $result['posts'] ) . "</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- onlineUsers --*/
function onlineUsers($active) {
$IPBHTML = "";
$IPBHTML .= "<div class='general_box clearfix' id='portal_active_users'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;section=online", "public",'' ), "", "" ) . "\">{$this->lang->words['online_title']}</a></h3>
	<div class='inner_portal_box'>
		<!--<span>" . sprintf( $this->lang->words['online_breakdown'], intval($active['TOTAL']) ) . "</span>-->
		<span class='desc'>" . sprintf( $this->lang->words['online_split'], intval($active['MEMBERS']), intval($active['visitors']), intval($active['ANON']) ) . "</span>
		<br /><br />
		<p>
			<span class='name'>" . implode( ",</span> <span class='name'>", $active['NAMES'] ) . "</span>					
		</p>
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- pollWrapper --*/
function pollWrapper($content="",$tid="") {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("topic", "0" ) . "
<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$tid}", "public",'' ), "", "" ) . "'>{$this->lang->words['poll_title']}</a></h3>
	{$content}
</div>
<br />";
return $IPBHTML;
}

/* -- siteNavigation --*/
function siteNavigation($links=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['siteNavigation'] ) )
{
$count_ac2c2c7e329641b8315d6fb38dffcb38 = is_array($this->functionData['siteNavigation']) ? count($this->functionData['siteNavigation']) : 0;
$this->functionData['siteNavigation'][$count_ac2c2c7e329641b8315d6fb38dffcb38]['links'] = $links;
}
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['links_title']}</h3>
	<div class='inner_portal_box'>
		<ul>
			".$this->__f__67638da0359a773eb107109e8a768d14($links)."		</ul>
	</div>
</div>
<br />";
return $IPBHTML;
}


function __f__67638da0359a773eb107109e8a768d14($links=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $links as $link )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li>&bull; <a href=\"{$link[1]}\">{$link[2]}</a></li>		
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- skeletonTemplate --*/
function skeletonTemplate() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['skeletonTemplate'] ) )
{
$count_f8def992e88cc95cee0356a15df19803 = is_array($this->functionData['skeletonTemplate']) ? count($this->functionData['skeletonTemplate']) : 0;
}
$IPBHTML .= "<!--
	SKINNOTE: Remember boxes are also in skin_gallery_portal, skin_blog_portal and skin_downloads_external
	-The striping doesn't add the proper padding like the board index does
	-Poll is kinda ugly
	-Print and Email should be icons.  Note that I also used \"moderation_bar\" class for that row, which isn't necessarily
		semantic, but displays fine - your call on whether to change it
-->
" . ((!$this->settings['disable_lightbox']) ? ("
" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_lightbox' ) ? $this->registry->getClass('output')->getTemplate('global')->include_lightbox() : '' ) . "
") : ("")) . "
<div id='portal_articles' class='left'>
	<!--MAIN-->
	 <!--::recent_topics_last_x::-->
	 <!--END MAIN-->
</div>
<div id='index_stats' class='portal left'>
	<!-- LEFT -->
	 <!--::portal_sitenav::-->
	 <!--::online_users_show::-->
	 <!--::blogs_show_last_updated_x::-->
	 <!--::recent_downloads_last_x::-->
	 <!--::gallery_show_random_image::-->
	 <!--::calendar_show_current_month::-->
	 <!--::poll_show_poll::-->
	 <!--::recent_topics_discussions_last_x::-->
	 <!--::portal_affiliates::-->
	 <!--END LEFT-->
</div>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_highlighter' ) ? $this->registry->getClass('output')->getTemplate('global')->include_highlighter(1) : '' ) . "
<script type='text/javascript'>
	// Resize images
	$$('.post', '.poll').each( function(elem){
		ipb.global.findImgs( $( elem ) );
	});
</script>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>