<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:28:05 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['boardIndexTemplate'] = array('showSubForumsLit','isNotLast','subforums','canSeeLastInfoRedirect','hasUnreadClass','hasUnread','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','lastPosterID','hideDateUrl','hideLastInfo','canSeeLastInfo','forumRedirect','forums','canSeeLastInfoHeader','cat_has_forums','categories','side_blocks','markerhasunread','markernotredirect','markerforums','markerhasforums','markercategories','boardIndexTop','sideBarEnabledL','sidebarclosed','cats_forums','sidebarclosed2','sideBarEnabled2','markercatforums','showTotals','reputationTypeTitle','reputationType','reputationEnabled','statsLinks','onlineListEnabled','showActive','activeNames');
$this->_funcHooks['boardIndexTopicsBeingViewed'] = array('users_hook');
$this->_funcHooks['hookFacebookActivity'] = array('fbAppIdPresent');
$this->_funcHooks['hookRecentTopics'] = array('topics_hook','recenttopics');
$this->_funcHooks['hooksos_topicosrecentes_parseTopic'] = array('notLastFt','topicsForumTrail','haslastpage','pages','hasmodlinks','hasPrefix','hasTags','multipages','queuedpostsImg','deletedPostsImg','isHot','replylang','isLink');
$this->_funcHooks['hooksos_topicosrecentes_tema1'] = array('topicosrecentes_hook');
$this->_funcHooks['hooksos_topicosrecentesAjax_tema1'] = array('topicosrecentes_hook');
$this->_funcHooks['hookTagCloud'] = array('eachTag');
$this->_funcHooks['sos32_timespent_sidebar'] = array('topics_hook','recenttopics');
$this->_funcHooks['statusReplies'] = array('canDelete','isFirstCycle','innerLoop');
$this->_funcHooks['statusUpdates'] = array('canDelete','isLocked','canLock','noLocked','cImg','hasRepliesMain','hasRepliesButCannotReply','canReplyMain','hasMore','hasReplies','canReply','outerLoop');


}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTemplate'] ) )
{
$count_db07e01dce18914da5418b448b1bf78b = is_array($this->functionData['boardIndexTemplate']) ? count($this->functionData['boardIndexTemplate']) : 0;
$this->functionData['boardIndexTemplate'][$count_db07e01dce18914da5418b448b1bf78b]['lastvisit'] = $lastvisit;
$this->functionData['boardIndexTemplate'][$count_db07e01dce18914da5418b448b1bf78b]['stats'] = $stats;
$this->functionData['boardIndexTemplate'][$count_db07e01dce18914da5418b448b1bf78b]['cat_data'] = $cat_data;
$this->functionData['boardIndexTemplate'][$count_db07e01dce18914da5418b448b1bf78b]['show_side_blocks'] = $show_side_blocks;
$this->functionData['boardIndexTemplate'][$count_db07e01dce18914da5418b448b1bf78b]['side_blocks'] = $side_blocks;
}

$this->templateVars['sidebar_enabled'] = "$show_side_blocks";
$this->__default__templateVars['sidebar_enabled'] = "$show_side_blocks";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "" . ((true) ? ("") : ("")) . "
<div id='board_index' class='ipsLayout " . (($this->templateVars['sidebar_enabled']) ? ("ipsLayout_withright") : ("")) . " ipsLayout_largeright clearfix " . ((IPSCookie::get('hide_sidebar') == '1') ? ("no_sidebar") : ("")) . "'>	
	<div id='categories' class='ipsLayout_content clearfix'>
	<!-- CATS AND FORUMS -->
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__fff61d548c8ee614f95a8ae1b749da52($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
	" . (($this->templateVars['sidebar_enabled']) ? ("<div id='index_stats' class='ipsLayout_right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">
			".$this->__f__0f875631e933d2ba211a8a990fc58076($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		</div>
		<a href='#' id='toggle_sidebar' title='{$this->lang->words['toggle_sidebar']}' data-closed=\"{$this->lang->words['_laquo']}\" data-open=\"&times;\">&nbsp;</a>") : ("")) . "
</div>
<script type='text/javascript'>
//<![CDATA[
	var markerURL  = ipb.vars['base_url'] + \"app=forums&module=ajax&section=markasread&i=1\"; // Ajax URL so don't use &amp;
	var unreadIcon = \"<img src='{$this->settings['img_url']}/f_icon_read.png' />\";
	
	" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
		".$this->__f__619bf3adaa09236021b11cfd9f52d6f0($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."	") : ("")) . "
//]]>
</script>
" . (($this->settings['show_totals']) ? ("
	<div id='board_stats'>		
		<ul class='ipsType_small ipsList_inline'>
			<li class='clear'>
				<span class='value'>{$stats['info']['total_posts']}</span>
				{$this->lang->words['total_posts']}
			</li>
			<li class='clear'>
				<span class='value'>{$stats['info']['mem_count']}</span>
				{$this->lang->words['total_members']}
			</li>
			<li class='clear'>
				" . IPSMember::makeProfileLink( $stats['info']['last_mem_name'], $stats['info']['last_mem_id'], $stats['info']['last_mem_seo'], 'value' ) . "
				{$this->lang->words['newest_member']}
			</li>
			<li class='clear' data-tooltip=\"{$stats['info']['most_time']}\">
				<span class='value'>{$stats['info']['most_online']}</span>
				{$this->lang->words['online_at_once']}
			</li>
		</ul>
	</div>
") : ("")) . "
<div id='board_statistics' class='statistics clearfix'>
	<ul id='stat_links' class='ipsList_inline right ipsType_small'>
		" . ((1==1) ? ("<!-- Hook point -->
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=leaders", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_forum_leaders_title']}\">{$this->lang->words['sm_forum_leaders']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_all_posters_title']}\">{$this->lang->words['sm_today_posters']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;max_results=20&amp;sort_key=posts&amp;sort_order=desc&amp;filter=ALL", "public",'' ), "false", "" ) . "\" title=\"{$this->lang->words['sm_overall_posters_title']}\">{$this->lang->words['sm_overall_posters']}</a></li>
			" . (($this->settings['reputation_enabled']) ? ("<li>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=reputation&amp;section=most", "public",'' ), "most_liked", "most_liked" ) . "\" title=\"" . (($this->settings['reputation_point_types'] == 'like') ? ("{$this->lang->words['most_rep_likes']}") : ("{$this->lang->words['most_rep_rep']}")) . "\">
						" . (($this->settings['reputation_point_types'] == 'like') ? ("
							{$this->lang->words['most_rep_likes']}
						") : ("
							{$this->lang->words['most_rep_rep']}
						")) . "
					</a>
				</li>") : ("")) . "") : ("")) . "
	</ul>
	
	" . (($this->settings['show_active'] && $this->memberData['gbw_view_online_lists']) ? ("<h4 class='statistics_head'>" . sprintf( $this->lang->words['online_right_now'], $stats['TOTAL'] ) . " {$this->lang->words['active_users']}</h4>
		<p class='statistics_brief desc'>
			" . sprintf( $this->lang->words['active_users_detail'], $stats['MEMBERS'], $stats['GUESTS'], $stats['ANON'] ) . "
			" . (($this->settings['allow_online_list']) ? ("&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_order=desc", "public",'' ), "", "" ) . "' title='{$this->lang->words['online_link']}'>({$this->lang->words['online_link']})</a>") : ("")) . "
		</p>") : ("")) . "
	" . ((count($stats['NAMES']) && $this->settings['show_active']) ? ("
		<br />
		<p>
			<span class='name'>" . implode( ",</span> <span class='name'>", $stats['NAMES'] ) . "</span>
		</p>
	") : ("")) . "<!--hook.if.skin_boards.boardIndexTemplate.activeNames.post.endif-->
</div>";
return $IPBHTML;
}


function __f__0fdeb658beab53529830d3e762020e74($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
																" . (($__data[3]) ? ("<li class='unread'>") : ("<li>")) . "
																	<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", "public",'' ), "{$__data[2]}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars($__data[1]) ) . "'>{$__data[1]}</a>" . ((empty($__data[4] )) ? (",") : ("")) . "
																</li>
															
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f38e6ba03d04d3dbede3b7d05651290a($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
										" . (($forum_data['redirect_on']) ? ("<tr class='redirect_forum' id='f_{$forum_data['id']}'>
												<td class='col_c_icon'>
													<img src='{$this->settings['img_url']}/f_redirect.png' />
												</td>
												<td " . (($this->memberData['gbw_view_last_info']) ? ("colspan='2'") : ("")) . " class='col_c_forum'>
													<h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a></h4>
													<p class='desc'>{$forum_data['description']}</p>
												</td>
												<td class='desc'>
													<ul class='last_post ipsType_small'>
														<li class='desc lighter'><em>" . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . " {$this->lang->words['rd_hits']}</em></li>
													</ul>
												</td>
											</tr>") : ("<tr class='" . (($forum_data['_has_unread']) ? ("unread") : ("")) . "'>
												<td class='col_c_icon'>
													" . (($forum_data['_has_unread']) ? ("
														<a id='forum_img_{$forum_data['id']}' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "\" data-tooltip=\"{$this->lang->words['bi_markread']}\" class='forum_marker'><img src='{$this->settings['img_url']}/f_icon.png' /></a>
													") : ("
														<img src='{$this->settings['img_url']}/f_icon_read.png' />
													")) . "
												</td>
												<td class='col_c_forum'>
													
													<h4>
														" . ((!empty($forum_data['_has_queued_and_can_see_icon'])) ? ("
															<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;modfilter=unapproved", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "' title='{$this->lang->words['view_unapproved']}' class='ipsBadge ipsBadge_orange' data-tooltip=\"" . sprintf( $this->lang->words['f_queued'], $forum_data['queued_topics'], $forum_data['queued_posts']) . "\" style='vertical-align: top'>{$this->lang->words['f_queued_badge']}</a>
														") : ("")) . "
														<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a>
													</h4>
														
													" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums']) ? ("
														<br />
														<ol class='ipsList_inline ipsType_small subforums' id='subforums_{$forum_data['id']}'>
															".$this->__f__0fdeb658beab53529830d3e762020e74($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."														</ol>
													") : ("")) . "
																					
													<p class='desc __forum_desc ipsType_small'>{$forum_data['description']}</p>											
												</td>
												<td class='col_c_stats ipsType_small'>
													<ul>
														<li><strong>{$forum_data['topics']}</strong> {$this->lang->words['topics']}</li>
														<li><strong>{$forum_data['posts']}</strong> {$this->lang->words['replies']}</li>
													</ul>
												</td>
												" . (($this->memberData['gbw_view_last_info']) ? ("<td class='col_c_post'>
													" . (($forum_data['hide_last_info']) ? ("
														<ul class='last_post ipsType_small'>
															<li class='desc lighter'><em>{$this->lang->words['f_protected']}</em></li>
														</ul>
													") : ("" . (($forum_data['_hide_last_date']) ? ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => '' )) : '' ) . "
														") : ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => sprintf( $this->lang->words['bindex_userphoto_alt'], $forum_data['last_title'], $forum_data['members_display_name'] ) )) : '' ) . "
														")) . "
														<ul class='last_post ipsType_small'>
															" . ((!$forum_data['last_id']) ? ("
																<li class='desc lighter'><em>{$this->lang->words['f_none']}</em></li>
															") : ("<li>
																	{$forum_data['last_topic_title']}
																</li>
																" . (($forum_data['last_poster_id']) ? ("
																	<li>{$this->lang->words['by']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($forum_data) : '' ) . "</li>
																") : ("")) . "
																" . (($forum_data['_hide_last_date']) ? ("
																	<li class='desc lighter blend_links'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "</li>
																") : ("
																	<li class='desc lighter blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", "public",'' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "</a></li>
																")) . "")) . "
														</ul>")) . "
												</td>") : ("")) . "
											</tr>")) . "
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__fff61d548c8ee614f95a8ae1b749da52($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.categories.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("<div id='category_{$_data['cat_data']['id']}' class='category_block block_wrap'>
						<h3 class='maintitle'>
							<a class='toggle right' href='#' title=\"" . sprintf( $this->lang->words['toggle_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "\">" . sprintf( $this->lang->words['toggle_cat'], $_data['cat_data']['name'] ) . "</a> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", "public",'' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='" . sprintf( $this->lang->words['view_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "'>{$_data['cat_data']['name']}</a>
						</h3>
						<div class='ipsBox table_wrap'>
							<div class='ipsBox_container'>
								<table class='ipb_table' summary=\"{$this->lang->words['forums_in_cat']} '{$_data['cat_data']['name']}'\">
									<tr class='header hide'>
										<th scope='col' class='col_c_icon'>&nbsp;</th>
										<th scope='col' class='col_c_forum'>{$this->lang->words['cat_name']}</th>
										<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>
										" . (($this->memberData['gbw_view_last_info']) ? ("<th scope='col' class='col_c_post'>{$this->lang->words['last_post_info']}</th>") : ("")) . "
									</tr>
									<!-- / CAT HEADER -->
									".$this->__f__f38e6ba03d04d3dbede3b7d05651290a($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."								</table>
							</div>
						</div>
						<br />
					</div>") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__0f875631e933d2ba211a8a990fc58076($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.side_blocks.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $side_blocks as $block )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				{$block}
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__19f599efd9e26015f01b0f199a463050($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ((!$forum_data['redirect_on']) ? ("" . (($forum_data['_has_unread']) ? ("
	ipb.global.registerMarker( \"forum_img_{$forum_data['id']}\", \"{$forum_data['img_new_post']}\", markerURL + \"&forumid={$forum_data['id']}\" );
						") : ("")) . "") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__619bf3adaa09236021b11cfd9f52d6f0($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				".$this->__f__19f599efd9e26015f01b0f199a463050($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- boardIndexTopicsBeingViewed --*/
function boardIndexTopicsBeingViewed($users) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTopicsBeingViewed'] ) )
{
$count_ebe910553bd78b39fb3c0b380ffd9270 = is_array($this->functionData['boardIndexTopicsBeingViewed']) ? count($this->functionData['boardIndexTopicsBeingViewed']) : 0;
$this->functionData['boardIndexTopicsBeingViewed'][$count_ebe910553bd78b39fb3c0b380ffd9270]['users'] = $users;
}
$IPBHTML .= "" . ((is_array( $users ) && count( $users )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['topics_being_viewed']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__8bfb5a20cbc58ecdf3792f155251ce11($users)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__8bfb5a20cbc58ecdf3792f155251ce11($users)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $users as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='clearfix'>
				" . (($r['member_id']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['starter_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['topic_created_by']} {$r['members_display_name']} {$this->lang->words['topic_created_in']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0)) . "' class='ipsUserPhotoLink'>
				") : ("")) . "
				<img src='{$r['pp_mini_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$r['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_mini left' />
				" . (($r['member_id']) ? ("
					</a>
				") : ("")) . "
				<div class='list_content'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['location_1_id']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' class='ipsType_small' title='{$this->lang->words['view_topic']}'>" . IPSText::truncate($r['title'],35) . "</a>
					<p class='desc ipsType_smaller'>
						{$r['total']} " . (($r['total'] > 1) ? ("{$this->lang->words['users_reading']}") : ("{$this->lang->words['user_reading']}")) . "
					</p>
				</div>
			</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- guestMessageSidebar --*/
function guestMessageSidebar() {
$IPBHTML = "";
$IPBHTML .= "<!-- Guest Message {$this->settings['board_name']} -->
<div class='ipsSideBlock'>
    <h3>{$this->settings['gm_title']}</h3>
    <div class='_sbcollapsable'>
         {$this->settings['gm_message']}
         <!-- Removal of copyrights without permission is illegal and prohibited. Copyright must be viewable to the naked eye unless copyright removal purchased. --> 
         
</div>
<!-- / Guest Message {$this->settings['board_name']} -->";
return $IPBHTML;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($updates=array()) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.status.js\"></script>
<div class='ipsSideBlock clearfix' id='statusHook'>
	<h3>{$this->lang->words['recent_status_updates']}</h3>
	<div class='_sbcollapsable'>
		<div id=\"status_wrapper\">
			<div id=\"status_wrapper_inside\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusUpdates($updates, 1, 1) : '' ) . "</div>
			<div class=\"status_main_content ipsType_small\" style='text-align: center'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "'>{$this->lang->words['viewallupdates']}</a>
			</div>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- hookFacebookActivity --*/
function hookFacebookActivity() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookFacebookActivity'] ) )
{
$count_eb684c21f892ace0a1f552ced284bf2d = is_array($this->functionData['hookFacebookActivity']) ? count($this->functionData['hookFacebookActivity']) : 0;
}
$IPBHTML .= "" . ((IPSLib::fbc_enabled()) ? ("
<div class='general_box clearfix'>
	<h3>{$this->lang->words['hook_facebookactivity']}</h3>
	<div  class='block_list clearfix _sbcollapsable'>
		<div><fb:activity site=\"\" width=\"270\" height=\"300\" header=\"false\" border_color=\"#FFF\" colorscheme=\"light\" /></div>
	</div>
</div><div id=\"fb-root\"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '{$this->settings['fbc_appid']}', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/{$this->settings['fb_locale']}/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentTopics'] ) )
{
$count_e1c4e86eacb46dc2026ca2381b0c8c89 = is_array($this->functionData['hookRecentTopics']) ? count($this->functionData['hookRecentTopics']) : 0;
$this->functionData['hookRecentTopics'][$count_e1c4e86eacb46dc2026ca2381b0c8c89]['topics'] = $topics;
}
$IPBHTML .= "" . ((is_array( $topics ) && count( $topics )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['recently_added_topics']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__0699c36c4ffc5117ea47ee9549c92ec8($topics)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__0699c36c4ffc5117ea47ee9549c92ec8($topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r) : '' ) . "
			<div class='list_content'>
				<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "\" rel='bookmark' class='ipsType_small' title='" . strip_tags($r['topic_title']) . " {$this->lang->words['topic_started_on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"LONG", 0)) . "'>{$r['topic_title']}</a>
				<p class='desc ipsType_smaller'>
					" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "
					- " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0)) . "
				</p>
			</div>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentes_parseTopic --*/
function hooksos_topicosrecentes_parseTopic($r=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentes_parseTopic'] ) )
{
$count_94d02d1b32f389ac21d27eb23ea2ee5c = is_array($this->functionData['hooksos_topicosrecentes_parseTopic']) ? count($this->functionData['hooksos_topicosrecentes_parseTopic']) : 0;
$this->functionData['hooksos_topicosrecentes_parseTopic'][$count_94d02d1b32f389ac21d27eb23ea2ee5c]['r'] = $r;
}

$author = IPSMember::makeProfileLink(IPSMember::makeNameFormatted( $r['topic_data']['nome1'], $r['topic_data']['grupo1']), $r['topic_data']['starter_id']);

$lastposter = IPSMember::makeProfileLink(IPSMember::makeNameFormatted( $r['topic_data']['members_display_name'], $r['topic_data']['member_group_id']), $r['topic_data']['last_poster_id']);
$IPBHTML .= "<li>
	<table class=\"ipb_table topic_list hover_rows\">
		<tr class='__topic " . ((!$r['topic_data']['folder_img']['is_read']) ? ("unread") : ("")) . " expandable' id='trow_{$r['topic_data']['tid']}' data-tid=\"{$r['topic_data']['tid']}\" data-timestamp=\"{$r['topic_data']['last_post']}\">
			<td class='col_f_icon altrow short'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'generateTopicIcon' ) ? $this->registry->getClass('output')->getTemplate('global_other')->generateTopicIcon($r['topic_data']['folder_img'], isset($r['topic_data']['_unreadUrl']) ? $r['topic_data']['_unreadUrl'] : '') : '' ) . "
			</td>
			
			<td class='col_f_content " . (($this->memberData['is_mod'] == 1 || $r['forum_data']['permissions']['TopicSoftDelete']) ? (" with_mod_links") : ("")) . "'>
				" . ((!empty($r['topic_data']['tags']['formatted']['prefix'])) ? ("
					{$r['topic_data']['tags']['formatted']['prefix']}
				") : ("")) . "
				<h4>{$r['topic_data']['prefix']} " . (($r['topic_data']['topic_hasattach']) ? ("<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=attach&amp;tid={$r['topic_data']['tid']}", "public",'' ), "", "" ) . "\" title=\"" . intval($r['topic_data']['topic_hasattach']) . " {$this->lang->words['topic_attach']}\" onclick=\"return ipb.forums.retrieveAttachments( {$r['topic_data']['tid']} );\">" . $this->registry->getClass('output')->getReplacement("post_attach_link") . "</a> ") : ("")) . "<a{$r['topic_data']['style']} id=\"tid-link-{$r['topic_data']['tid']}\" href=\"{$r['topic_data']['_url']}\" title='{$this->lang->words['topic_started_on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['start_date'],"LONG", 0)) . "' class='topic_title'>{$r['topic_data']['title']}</a></h4>
				<br />
				<span class='desc lighter blend_links'>
										" . sprintf( $this->lang->words['topic_started_by'], $author ) . " " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['start_date'],"DATE", 0)) . "
					{$this->lang->words['in_last_topic']}
					".$this->__f__478065b5b33bce20b8e762d554ab17d2($r)."					" . ((isset($r['topic_data']['tags']) AND $r['topic_data']['tags']) ? ("
						&nbsp; <img src='{$this->settings['img_url']}/icon_tag.png' /> {$r['topic_data']['tags']['formatted']['truncatedWithLinks']}
					") : ("")) . "
				</span>
				" . ((isset( $r['topic_data']['pages'] ) AND is_array( $r['topic_data']['pages'] ) AND count( $r['topic_data']['pages'] )) ? ("
					<ul class='mini_pagination'>
					".$this->__f__e4587ebfcc9d22097d3bf8382c7042b0($r)."					</ul>
				") : ("")) . "
			</td>
			<td class='col_f_preview __topic_preview'>
				" . (($this->registry->permissions->check( 'read', $r['forum_data'] )) ? ("
					<a href='{$r['topic_data']['_url']}' class='expander closed' title='{$this->lang->words['view_topic_preview']}'>&nbsp;</a>
				") : ("")) . "
			</td>
			<td class='col_f_views desc blend_links'>
				<ul>
					<li>
						" . ((($this->memberData['is_mod'] AND $r['topic_data']['_hasqueued'])) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;modfilter=invisible_posts", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_uapproved_posts']}' data-tooltip=\"" . sprintf( $this->lang->words['topic_queued_count'], $r['topic_data']['topic_queuedposts'] ) . "\"><img src='{$this->settings['img_url']}/bullet_error.png' alt='' /></a>
						") : ("")) . "
						" . ((($r['forum_data']['permissions']['PostSoftDeleteSee'] AND $r['topic_data']['topic_deleted_posts'])) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;modfilter=deleted_posts", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_deleted_posts']}'><img src='{$this->settings['img_url']}/bullet_delete.png' alt='' /></a>
						") : ("")) . "
						" . (($r['topic_data']['state'] != 'link') ? ("" . (($r['topic_data']['folder_img']['is_hot']) ? ("
								<span class='ipsBadge ipsBadge_orange'>{$this->lang->words['topic_is_hot']}</span>&nbsp;
							") : ("")) . "
							<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=who&amp;t={$r['topic_data']['tid']}", "public",'' ), "", "" ) . "\" onclick=\"return ipb.forums.retrieveWhoPosted( {$r['topic_data']['tid']} );\">" . $this->registry->getClass('class_localization')->formatNumber( $r['topic_data']['posts'] ) . " " . ((intval($r['topic_data']['posts']) == 1) ? ("{$this->lang->words['reply']}") : ("{$this->lang->words['replies']}")) . "</a>") : ("")) . "
					</li>
					<li class='views desc'>" . $this->registry->getClass('class_localization')->formatNumber( $r['topic_data']['views'] ) . " {$this->lang->words['views']}</li>
				</ul>
			</td>
			<td class='col_f_post'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['topic_data']['last_poster_id']}", "public",'' ), "{$r['topic_data']['seo_last_name']}", "showuser" ) . "' class='ipsUserPhotoLink left'>
					<img src='{$r['topic_data']['pp_small_photo']}' class='ipsUserPhoto ipsUserPhoto_mini' />
				</a>
				<ul class='last_post ipsType_small'>
									<li>{$lastposter}</li>
					<li>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;view=getlastpost", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['goto_last_post']}'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['topic_data']['last_post'],"DATE", 0)) . "</a>
					</li>								
				</ul>
			</td>
		</tr>
	</table>
</li>";
return $IPBHTML;
}


function __f__478065b5b33bce20b8e762d554ab17d2($r=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $r['topic_data']['forumBreadcrumb'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$f[1]}", "public",'' ), "{$f[2]}", "showforum" ) . "'>{$f[0]}</a>&nbsp;" . (($i+1 != count( $r['topic_data']['forumBreadcrumb'] )) ? ("" . $this->registry->getClass('output')->getReplacement("f_nav_sep") . "") : ("")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e4587ebfcc9d22097d3bf8382c7042b0($r=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $r['topic_data']['pages'] as $page )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							" . (($page['last']) ? ("
								<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;st={$page['st']}", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']} {$this->lang->words['_rarr']}</a></li>
							") : ("
								<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['topic_data']['tid']}&amp;st={$page['st']}", "public",'' ), "{$r['topic_data']['title_seo']}", "showtopic" ) . "\" title='{$this->lang->words['topic_goto_page']} {$page['page']}'>{$page['page']}</a></li>
							")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentes_tema1 --*/
function hooksos_topicosrecentes_tema1($topics=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentes_tema1'] ) )
{
$count_0dff41634d77f74229248013698aded9 = is_array($this->functionData['hooksos_topicosrecentes_tema1']) ? count($this->functionData['hooksos_topicosrecentes_tema1']) : 0;
$this->functionData['hooksos_topicosrecentes_tema1'][$count_0dff41634d77f74229248013698aded9]['topics'] = $topics;
}

if ( $this->memberData['member_id'] AND $this->memberData['topicosrecentes_showdqtd'] )
		{
			$nr = $this->memberData['recenttopics_qtd'];
		}
		else
		{
			$nr = $this->settings['topicosrecentes_nr'];
		}
$IPBHTML .= "<script src=\"{$this->settings['public_dir']}js/ips.recentTopicsHook.js\" type=\"text/javascript\"></script>
<script src=\"{$this->settings['public_dir']}js/ips.forums.js\" type=\"text/javascript\"></script>
	  <script type=\"text/javascript\">
	ipb.recentTopics.updateInterval = parseInt( {$this->settings['topicosrecentes_updateInterval']} );
		ipb.recentTopics.maxElements	= parseInt( {$nr} );
	ipb.recentTopics.img_disable    = parseInt({$this->settings['topicosrecentes_img_disable']});
</script>

<div id='recentTopicsWrapper' class='category_block block_wrap'>
	<h3 class='maintitle'>
	<span class=\"right\"><ul class=\"ipsFilterbar ipsList_inline ipsType_small\">
	" . (($this->memberData['member_id']) ? ("<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=usercp&amp;tab=core&amp;area=recenttopics", "public",'' ), "", "" ) . "\" rel=\"nofollow\"><img src='{style_image_url}/cog.png' title='{$this->lang->words['recenttopics_settings']}' alt='+' /></a></li>") : ("")) . "
	                <a class='toggle right' href='#' title=\"{$this->lang->words['toggle_cat']}\">
	        {$this->lang->words['toggle_cat']}</a></ul>
	                        </span>
	{$this->settings['topicosrecentes_title']}</h3>
	<div class='ipsBox table_wrap'>
		<div class='ipsBox_container'>
			<table class='ipb_table topic_list hover_rows'>
				<tr class='header hide'>
					<th scope='col' class='col_f_icon'>&nbsp;</th>
					<th scope='col' class='col_f_topic'>{$this->lang->words['forum_topic']}</th>
					<th scope='col' class='col_f_starter short'>{$this->lang->words['forum_started_by']}</th>
					<th scope='col' class='col_f_views stats'>{$this->lang->words['forum_stats']}</th>
					<th scope='col' class='col_f_post'>{$this->lang->words['forum_last_post_info']}</th>
				</tr>
			</table>
			<!-- BEGIN TOPICS -->
			<ul id='recentTopics_table'>
				".$this->__f__f7f796a963bb3810371c6a013416c077($topics)."			</ul>
		</div>
	</div>
</div>
<br />";
return $IPBHTML;
}


function __f__f7f796a963bb3810371c6a013416c077($topics=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'hooksos_topicosrecentes_parseTopic' ) ? $this->registry->getClass('output')->getTemplate('boards')->hooksos_topicosrecentes_parseTopic($r) : '' ) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hooksos_topicosrecentesAjax_tema1 --*/
function hooksos_topicosrecentesAjax_tema1($topics=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hooksos_topicosrecentesAjax_tema1'] ) )
{
$count_ac234f7fe23b5802a2e7a164df404c63 = is_array($this->functionData['hooksos_topicosrecentesAjax_tema1']) ? count($this->functionData['hooksos_topicosrecentesAjax_tema1']) : 0;
$this->functionData['hooksos_topicosrecentesAjax_tema1'][$count_ac234f7fe23b5802a2e7a164df404c63]['topics'] = $topics;
}
$IPBHTML .= "".$this->__f__e08d1f1b6187a6ede5d04b1bca684ede($topics)."";
return $IPBHTML;
}


function __f__e08d1f1b6187a6ede5d04b1bca684ede($topics=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'hooksos_topicosrecentes_parseTopic' ) ? $this->registry->getClass('output')->getTemplate('boards')->hooksos_topicosrecentes_parseTopic($r) : '' ) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookTagCloud'] ) )
{
$count_9982441add28cbc2d6427a6572b2ebf4 = is_array($this->functionData['hookTagCloud']) ? count($this->functionData['hookTagCloud']) : 0;
$this->functionData['hookTagCloud'][$count_9982441add28cbc2d6427a6572b2ebf4]['tags'] = $tags;
}
$IPBHTML .= "<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['popular_tags']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_inline'>
		".$this->__f__f002cfce8c23eef231cc4a186b23def0($tags)."		</ul>
	</div>
</div>";
return $IPBHTML;
}


function __f__f002cfce8c23eef231cc4a186b23def0($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- sos32_timespent_sidebar --*/
function sos32_timespent_sidebar($users=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['sos32_timespent_sidebar'] ) )
{
$count_eb857f03f85383b2dbb9e2a6f0d81f0d = is_array($this->functionData['sos32_timespent_sidebar']) ? count($this->functionData['sos32_timespent_sidebar']) : 0;
$this->functionData['sos32_timespent_sidebar'][$count_eb857f03f85383b2dbb9e2a6f0d81f0d]['users'] = $users;
}
$IPBHTML .= "" . ((is_array( $users ) && count( $users )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>" . sprintf( $this->lang->words['time_spent_title'], $this->settings['sidebar_toponlineusers_registros'] ) . "</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__1cafec40e6eb6bcfc57d8eab3a4d06b2($users)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__1cafec40e6eb6bcfc57d8eab3a4d06b2($users=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $users as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$r['pp_mini_photo']}' alt=\"{$r['members_display_name']}{$this->lang->words['users_photo']}\" class='ipsUserPhoto ipsUserPhoto_mini' /></a>
			<div class='list_content'>
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "
				<p class='desc ipsType_smaller'>
					{$this->lang->words['time_spent']}: {$r['time']}
				</p>
			</div>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusReplies --*/
function statusReplies($replies=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusReplies'] ) )
{
$count_ac314e6bd532f96528bc6bdd63f9f195 = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_ac314e6bd532f96528bc6bdd63f9f195]['replies'] = $replies;
}
$IPBHTML .= "".$this->__f__238ada0c007a065b2b95cadfb1d24bcf($replies)."";
return $IPBHTML;
}


function __f__238ada0c007a065b2b95cadfb1d24bcf($replies=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div id='statusReply-{$reply['reply_id']}' class='ipsPad_half'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $reply, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$reply['members_display_name']) ) )) : '' ) . "
		<div class='list_content'>
			<div class='right lighter'>
				<span class='desc ipsType_smaller'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($reply['reply_date'],"manual{%d %b}", 0)) . "&nbsp;&nbsp;</span>
				<span class='desc mod_links ipsType_smaller'>
					" . (($reply['_canDelete']) ? ("<a href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}\" id=\"statusReplyDelete-{$reply['reply_status_id']}-{$reply['reply_id']}\" class=\"__sDR __dr{$reply['reply_status_id']}-{$reply['reply_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
				</span>
			</div>
			<strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($reply) : '' ) . "</strong>
			<p class='index_status_update ipsType_small'>{$reply['reply_content']}</p>
		</div>
	</div>
	" . (($__iteratorCount == count($replies)) ? ("
		<div id='statusReplyBlank-{$reply['reply_status_id']}' style='display: none'></div>
	") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusUpdates'] ) )
{
$count_f404be039703d8830ff97c3d13e679f0 = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_f404be039703d8830ff97c3d13e679f0]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_f404be039703d8830ff97c3d13e679f0]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_f404be039703d8830ff97c3d13e679f0]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "<script type=\"text/javascript\">
	ipb.status.maxReplies = " . intval($this->settings['su_max_replies']) . ";
	ipb.status.smallSpace = " . intval($smallSpace) . ";
	ipb.status.skin_group = 'boards';
</script>".$this->__f__8cb71c13d7b8d0e802eb027605fecdc6($updates,$smallSpace,$latestOnly)."";
return $IPBHTML;
}


function __f__8cb71c13d7b8d0e802eb027605fecdc6($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($this->memberData['member_id'] AND $latestOnly AND $status['member_id'] == $this->memberData['member_id']) ? ("
		<script type=\"text/javascript\">
			ipb.status.myLatest = {$status['status_id']};
		</script>
	") : ("")) . "
	<ul class='ipsList_withminiphoto status_list' id='statusWrap-{$status['status_id']}'>
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($status) : '' ) . "
			<div class='list_content'>
				<div id=\"statusContent-{$status['status_id']}\">
					<div class='right desc lighter'>
						<span class='desc mod_links ipsType_smaller'>
							" . (($status['_canDelete']) ? ("<a rel=\"nofollow\" href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusDelete-{$status['status_id']}\" class=\"__sD __d{$status['status_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
							<span id='statusUnlock-{$status['status_id']}' " . (($status['_isLocked'] AND $status['_canUnlock']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=unlockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusUnlockLink-{$status['status_id']}\" class=\"__sU __u{$status['status_id']}\">{$this->lang->words['status_unlock_link']}</a></span>
							<span id='statusLock-{$status['status_id']}' " . (($status['_canLock'] AND ! $status['_isLocked']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=lockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusLockLink-{$status['status_id']}\" class=\"__sL __l{$status['status_id']}\">{$this->lang->words['status_lock_link']}</a></span>
						</span>
						&nbsp;&nbsp;<span class='ipsType_smaller blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=single&amp;status_id={$status['status_id']}", "public",'' ), array($status['member_id'], $status['members_seo_name']), "members_status_single" ) . "'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($status['status_date'],"manual{%d %b}", 0)) . "</a></span>
					</div>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status) : '' ) . "
					<p class='index_status_update ipsType_small'>{$status['status_content']}</p>
					<span class='desc' id='statusToggle-{$status['status_id']}'>
						<img src=\"{$this->settings['img_url']}/icon_lock.png\" id='statusLockImg-{$status['status_id']}' alt=\"{$this->lang->words['status__locked']}\" " . ((!$status['status_is_locked']) ? ("style='display: none'") : ("")) . " />
						" . ((! $smallSpace AND $status['_creatorImg']) ? ("<img src=\"{$status['_creatorImg']}\" alt='' data-tooltip=\"{$this->lang->words['su_via']} {$status['_creatorText']}\" />") : ("")) . "
						" . (($status['_userCanReply']) ? ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller \">" . sprintf( $this->lang->words['view_comments_and_add'], $status['status_replies']) . "</a>
							") : ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">{$this->lang->words['add_comments_only']}</a>
							")) . "") : ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">" . sprintf( $this->lang->words['view_comments_only'], $status['status_replies']) . "</a>
							") : ("")) . "")) . "
					</span>
					<span class='desc' id='statusToggleOff-{$status['status_id']}' style='display:none'>
						<a href=\"#\" class=\"__sTO __to{$status['status_id']}\">{$this->lang->words['view_comments_collapse']}</a>
					</span>
				</div>
			</div>
			<div id=\"statusFeedback-{$status['status_id']}\" class='status_feedback' style='display:none'>
				<div class='ipsList_withtinyphoto status_list' id='statusReplies-{$status['status_id']}'>
					" . (($status['status_replies'] AND count( $status['replies'] )) ? ("" . (($status['status_replies'] > 3) ? ("
							<div class='status_mini_wrap row2 altrow' id='statusMoreWrap-{$status['status_id']}'>
								<img src=\"{$this->settings['img_url']}/comments.png\" alt=\"\" /> &nbsp;<a href=\"#\" id=\"statusMore-{$status['status_id']}\" class='__showAll __x{$status['status_id']}'>" . sprintf( $this->lang->words['status_show_all_x'], $status['status_replies'] ) . "</a>
							</div>
						") : ("")) . "
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusReplies($status['replies']) : '' ) . "") : ("
						<div id='statusReplyBlank-{$status['status_id']}' style='display: none'></div>
					")) . "
				</div>
				" . (($status['_userCanReply']) ? ("
					<div class='ipsList_withtinyphoto status_list status_reply clearfix ipsPad_half' id='statusReply-{$status['status_id']}'>
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $this->memberData, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) ) )) : '' ) . "
						<div class='list_content'>
							<form id='statusReplyForm-{$status['status_id']}' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
								<textarea class='status_textarea' rows='3' cols='50' name='comment-{$status['status_id']}' id='statusText-{$status['status_id']}'></textarea>
								<div class=\"status_submit\"><input type='submit' class='__submit input_submit' id='statusSubmit-{$status['status_id']}' value='{$this->lang->words['status__dfcomment']}' /></div>
							</form>
							<a href='#' class='__showform' id='statusReplyFormShow-{$status['status_id']}' style='display: none'>{$this->lang->words['status__addcomment']}</a>
						</div>
					</div>
					<script type='text/javascript'>
						if( $('statusReplyForm-{$status['status_id']}') ){
							$('statusReplyForm-{$status['status_id']}').hide();
						}
						if( $('statusReplyFormShow-{$status['status_id']}') ){
							$('statusReplyFormShow-{$status['status_id']}').show();
						}
					</script>
				") : ("")) . "
			</div>
		</li>
	</ul>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>