<ips:template parameters="$guidelines" />
{{if !\IPS\Request::i()->isAjax()}}
	{template="pageHeader" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('guidelines')"}
{{endif}}
<div class='ipsType_normal ipsType_richText ipsPad ipsBox'>
	{template="richText" group="global" app="core" location="global" params="\IPS\Member::loggedIn()->language()->addToStack('guidelines_value'), array('ipsType_normal')"}
</div>