<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 18 Sep 2018 13:12:24 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'meta_editor_done' => "Close Editor",
'meta_editor_no_admin' => "You must be logged in as an administrator to use the Live Meta Editor",
'meta_editor_title' => "Live Meta Tag Editor",
'meta_save' => "Save Tags",
'meta_tag_content' => "Content",
'meta_tag_title' => "Title",
'meta_tag_title_desc' => "e.g. 'description', 'keywords', 'robots', etc.",
'no_hook' => "You must ensure that the 'IP.SEO: Meta Tags and Google Analytics' hook is enabled before you can use the Live Meta Tag Editor.",
 ); 
