<ips:template parameters="$club, $activity, $fieldValues" />

{{if \IPS\Settings::i()->clubs_header != 'sidebar'}}
	{template="header" group="clubs" app="core" params="$club"}
{{endif}}

<div class='ipsColumns ipsColumns_collapsePhone'>
	<section class='ipsColumn ipsColumn_fluid'>
	
		{{if settings.clubs_require_approval and !$club->approved}}
			<div class='ipsBox ipsPad ipsSpacer_bottom ipsModerated'>
				<div class='ipsColumns ipsColumns_collapsePhone'>
		    		<div class='ipsColumn ipsColumn_fluid'>
						<div class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_tiny cClubStatus'>
							<i class='fa fa-eye-slash ipsPos_left ipsType_large'></i>
							<div>
								<h3 class='ipsType_reset ipsType_large'>{lang="club_unapproved"}</h3>
								<p class='ipsType_reset ipsType_medium'>
									{{if member.modPermission('can_access_all_clubs')}}
										{lang="club_unapproved_desc_mod"}
									{{else}}
										{lang="club_unapproved_desc_public"}
									{{endif}}
								</p>
							</div>
						</div>
					</div>
					{{if member.modPermission('can_access_all_clubs')}}
						<div class='ipsColumn ipsColumn_narrow'>
							<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_positive" href="{$club->url()->setQueryString( array( 'do' => 'approve', 'approved' => 1 ) )->csrf()}" data-confirm>
								{lang="approve"}
							</a>
						</div>
						<div class='ipsColumn ipsColumn_narrow'>
							<a class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_negative" href="{$club->url()->setQueryString( array( 'do' => 'approve', 'approved' => 0 ) )->csrf()}" data-confirm>
								{lang="delete"}
							</a>
						</div>
					{{endif}}
				</div>
			</div>
		{{endif}}

		{{$memberStatus = $club->memberStatus( \IPS\Member::loggedIn(), 2 );}}
		{template="nonMemberClubStatus" group="clubs" app="core" params="$club, $memberStatus"}
		
		{{if $club->canRead()}}
			<div class="ipsClearfix ipsSpacer_bottom">
				<div class="ipsPos_right">
					{template="follow" app="core" group="global" params="'core','club', $club->id, $club->followersCount()"}
				</div>
			</div>
		{{endif}}

		{{if $club->about || ( $club->location() && settings.clubs_locations && ( !\IPS\GeoLocation::enabled() ) ) || \IPS\Member\Club\CustomField::roots()}}
			<div class='ipsBox ipsPad ipsSpacer_bottom'>
				{{if $club->about}}
					<div>
						<h3 class='ipsType_minorHeading'>{lang="club_about_this_club"}</h3>
						<div class='ipsType_richText ipsType_medium'>
							{$club->about}
						</div>
					</div>
				{{endif}}
				{{if $club->location() && settings.clubs_locations && ( !\IPS\GeoLocation::enabled() )}}
					<div class='{{if $club->about}}ipsSpacer_top{{endif}}'>
						<h3 class='ipsType_minorHeading'>{lang="club_location"}</h3>
						<div class='ipsType_richText ipsType_medium'>
							{$club->location()}
						</div>
					</div>
				{{endif}}
				<hr class='ipsHr'>
				{{if \IPS\Member\Club\CustomField::roots()}}
					{{foreach \IPS\Member\Club\CustomField::roots() as $field}}
						{{if isset( $fieldValues[ "field_" . $field->id ] )}}
							<div class='ipsSpacer_bottom'>
								<h3 class='ipsType_minorHeading'>{$field->_title}</h3>
								<div class='ipsType_richText ipsType_medium'>
									{$field->displayValue( $fieldValues[ "field_" . $field->id ] )|raw}
								</div>
							</div>
						{{endif}}
					{{endforeach}}
				{{endif}}
			</div>
		{{endif}}

		{{if $club->isLeader() and $club->type === $club::TYPE_CLOSED and $pendingMembers = $club->members( array( $club::STATUS_REQUESTED ), NULL, NULL, 3 ) and \count( $pendingMembers )}}
			<div class='ipsBox ipsSpacer_bottom'>
				<h2 class='ipsType_sectionTitle ipsType_reset ipsType_medium'><i class='fa fa-lock' data-ipsTooltip title="{lang="club_requested_users_desc"}"></i> {lang="club_requested_users"}</h2>
				<div data-controller='core.front.clubs.requests'>
					{template="membersRows" group="clubs" params="$club, $pendingMembers"}
				</div>
			</div>
			<hr class='ipsHr'>
		{{endif}}

		{{if $club->canRead()}}
			<div class='ipsBox_alt'>
				<ol class="ipsStream ipsStream_withTimeline ipsList_reset ipsSpacer_top">
					<li class='ipsStreamItem_time'>{lang="club_whats_new"}</li>
					{{foreach $activity as $result}}
						{{if $result !== NULL}}
							{$result->html()|raw}
						{{endif}}
					{{endforeach}}
					<li class='ipsStreamItem_terminator'>&nbsp;</li>
				</ol>
			</div>
		{{endif}}
	</section>
</div>