<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 27 Jan 2012 09:00:04 +0000 by deniss
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'blog_loc_attach' => "Viewing Blog Attachment",
'blog_loc_blog' => "Viewing Blog",
'blog_loc_entry' => "Viewing Blog Entry",
'blog_loc_list' => "Viewing Blogs",
'blog_loc_post' => "Posting an entry or comment",
'blog_loc_show' => "Viewing Blogs",
'blog_loc_ucp' => "Using Control Panel",
 ); 
