<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 30 Jul 2011 10:12:28 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'error_no_dir' => "The directory 'sources/portal_plugins' does not exist. Create it and try again.",
'error_no_key' => "There is no matching plug-in for the key used to find it.",
'error_no_settings' => "There are no settings for this plug-in",
'main_title' => "Manage Portal Plug-ins",
'portal_main_key' => "Plug-in Title",
'portal_main_title' => "Registered Portal Plug-ins",
'portal_pop_desc' => "Tag Description",
'portal_pop_name' => "Tag Name",
'portal_pop_tags' => "Exportable Tags:",
'portal_row_menu_settings' => "Edit Settings...",
'portal_row_menu_view_tags' => "View Exportable Tags...",
 ); 
