<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 30 Jul 2011 10:12:28 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'aff_title' => "Recommended Sites",
'article_comment' => "comment",
'but_active' => "Active Topics",
'but_forums' => "Forums",
'comments_suffix' => "comments",
'discuss_title' => "Latest Discussions",
'email' => "Email",
'links_title' => "Site Navigation",
'online_breakdown' => "There are <strong>%s</strong> online users browsing:",
'online_split' => "%s members, %s visitors and %s anonymous users",
'online_title' => "Online Users",
'poll_title' => "Website Poll",
'portal_by' => "by",
'print' => "Print",
'read' => "Read",
'recent_comments' => "Comments",
'recent_read' => "Read",
'recent_topics' => "Featured Topics",
'times_last' => "times - last ",
'times_make' => "times - make a ",
 ); 
