<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:28:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_portal_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['articles'] = array('postMember','articles');
$this->_funcHooks['latestPosts'] = array('ismember','posts');
$this->_funcHooks['siteNavigation'] = array('links');


}

/* -- affiliates --*/
function affiliates($links="") {
$IPBHTML = "";
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['aff_title']}</h3>
	<div>
		{$this->settings['csite_fav_contents']}
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- articles --*/
function articles($articles) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['articles'] ) )
{
$count_15d3a593cc530e3a79d1397acd037bad = is_array($this->functionData['articles']) ? count($this->functionData['articles']) : 0;
$this->functionData['articles'][$count_15d3a593cc530e3a79d1397acd037bad]['articles'] = $articles;
}
$IPBHTML .= "<div class='master_list'>
	<h2 class='title'>{$this->lang->words['recent_topics']}</h2>
	".$this->__f__3bedfc57b2f18882d0c367b5c4ff3d9f($articles)."";
return $IPBHTML;
}


function __f__3bedfc57b2f18882d0c367b5c4ff3d9f($articles)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $articles as $post )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<div class='topic_reply' id='entry{$post['pid']}'>
			<h2 class='secondary'>
				<img src='{$post['pp_thumb_photo']}' alt=\"{$post['members_display_name']}{$this->lang->words['users_photo']}\" width='{$post['pp_thumb_width']}' height='{$post['pp_thumb_height']}' class='photo' />
				<a style=\"text-decoration:none\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['tid']}", "public",'' ), "{$post['title_seo']}", "showtopic" ) . "'>{$post['title']}</a>
				<span class='subtext'>
					" . (($post['member_id']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$post['member_id']}", "public",'' ), "{$post['members_seo_name']}", "showuser" ) . "'>{$post['members_display_name']}</a>:
					") : ("
						{$post['members_display_name']}:
					")) . "
					" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($post['post_date'],"long", 0)) . "
				</span>
			</h2>
			<div id=\"post-{$post['pid']}\" class='row post line_spacing'>
				{$post['post']}
			</div>
		</div>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- calendarWrap --*/
function calendarWrap($content="") {
$IPBHTML = "";
$IPBHTML .= "{$content}
<br />";
return $IPBHTML;
}

/* -- latestPosts --*/
function latestPosts($posts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['latestPosts'] ) )
{
$count_ccb54787c11f54f232aacd41bb457b50 = is_array($this->functionData['latestPosts']) ? count($this->functionData['latestPosts']) : 0;
$this->functionData['latestPosts'][$count_ccb54787c11f54f232aacd41bb457b50]['posts'] = $posts;
}

if ( ! isset( $this->registry->templateStriping['recent_topics'] ) ) {
$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['discuss_title']}</h3>
	<ul class='hfeed'>
				".$this->__f__469cf24dbf0b79b75f5a8792552666fc($posts)."	</ul>
</div>
<br />";
return $IPBHTML;
}


function __f__469cf24dbf0b79b75f5a8792552666fc($posts=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $posts as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$result['tid']}", "public",'' ), "{$result['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$result['title_display']}</a> {$this->lang->words['portal_by']} <address class=\"author vcard\">" . (($result['member_id']) ? ("<a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$result['member_id']}", "public",'' ), "{$result['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$result['members_display_name']}</a>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($result['member_id']) : '' ) . "") : ("{$result['members_display_name']}")) . "</address> <span class='date'>(<abbr class=\"published\" title=\"" . date( 'c', $result['post_date'] ) . "\">{$result['date']}</abbr>)</span>
			<br />{$this->lang->words['recent_read']}: " . $this->registry->getClass('class_localization')->formatNumber( $result['views'] ) . " &nbsp; {$this->lang->words['recent_comments']}: " . $this->registry->getClass('class_localization')->formatNumber( $result['posts'] ) . "</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- onlineUsers --*/
function onlineUsers($active) {
$IPBHTML = "";
$IPBHTML .= "<div class='general_box clearfix' id='portal_active_users'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;section=online", "public",'' ), "", "" ) . "\">{$this->lang->words['online_title']}</a></h3>
	<div>
		<!--<span>" . sprintf( $this->lang->words['online_breakdown'], intval($active['TOTAL']) ) . "</span>-->
		<span class='desc'>" . sprintf( $this->lang->words['online_split'], intval($active['MEMBERS']), intval($active['visitors']), intval($active['ANON']) ) . "</span>
		<br /><br />
		<p>
			<span class='name'>" . implode( ",</span> <span class='name'>", $active['NAMES'] ) . "</span>					
		</p>
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- pollWrapper --*/
function pollWrapper($content="",$tid="") {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("topic", "0" ) . "
<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$tid}", "public",'' ), "", "" ) . "'>{$this->lang->words['poll_title']}</a></h3>
	{$content}
</div>
<br />";
return $IPBHTML;
}

/* -- siteNavigation --*/
function siteNavigation($links=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['siteNavigation'] ) )
{
$count_aa8c4d85f591be4a7aced99ec5040e90 = is_array($this->functionData['siteNavigation']) ? count($this->functionData['siteNavigation']) : 0;
$this->functionData['siteNavigation'][$count_aa8c4d85f591be4a7aced99ec5040e90]['links'] = $links;
}
$IPBHTML .= "<div class='general_box'>
	<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['links_title']}</h3>
	<ul>
		".$this->__f__b1151aa0fce4bf837dc66b9e7696e822($links)."	</ul>
</div>
<br />";
return $IPBHTML;
}


function __f__b1151aa0fce4bf837dc66b9e7696e822($links=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $links as $link )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li>&bull; <a href=\"{$link[1]}\">{$link[2]}</a></li>		
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- skeletonTemplate --*/
function skeletonTemplate() {
$IPBHTML = "";
$IPBHTML .= "" . (($this->settings['_mobile_hide_nav'] = 1) ? ("") : ("")) . "
<div class='controls'>
		<div class='buttons'>
			<a class=\"button\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "act=idx", "public",'' ), "-", "act=idx" ) . "'>{$this->lang->words['but_forums']}</a>
		</div>
</div>
<div id='portal_articles' class='left'>
	<!--MAIN-->
	 <!--::recent_topics_last_x::-->
	 <!--END MAIN-->
</div>
<div id='index_stats' class='portal left'>
	<!-- LEFT -->
	 <!--END LEFT-->
</div>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_highlighter' ) ? $this->registry->getClass('output')->getTemplate('global')->include_highlighter(1) : '' ) . "
<script type='text/javascript'>
	// Resize images
	$$('.post', '.poll').each( function(elem){
		ipb.global.findImgs( $( elem ) );
	});
</script>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>