<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:28:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_classifieds_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['basic_item_info'] = array('forsaleorwanted');
$this->_funcHooks['category_view'] = array('sub_categories','items');
$this->_funcHooks['item_row'] = array('catssthumb','typebadge','typebadge','forsaleorwanted');
$this->_funcHooks['item_view'] = array('yesno','fieldtypetest','fieldinnerloop','grouploop','catssthumb');


}

/* -- answer_form --*/
function answer_form($item, $question, $editor, $post_key) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- basic_item_info --*/
function basic_item_info($item, $seller) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['basic_item_info'] ) )
{
$count_e34d66801a98ab21792594d38f5d76af = is_array($this->functionData['basic_item_info']) ? count($this->functionData['basic_item_info']) : 0;
$this->functionData['basic_item_info'][$count_e34d66801a98ab21792594d38f5d76af]['item'] = $item;
$this->functionData['basic_item_info'][$count_e34d66801a98ab21792594d38f5d76af]['seller'] = $seller;
}
$IPBHTML .= "<div class='panel'>
                    " . (($item['item_condition']) ? ("
                        <p>{$this->lang->words['cfds_condition']} - {$item['item_condition']}</p>
                    ") : ("")) . "
                    {$this->lang->words['cfds_price']} -
                        " . (($item['price'] != '0.00') ? (" " . ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], true ) . "") : ("" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_free']}
                                ") : ("
                                {$this->lang->words['cfds_wanted_noprice']}")) . "")) . "
                    <p>{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "</p>
</div>";
return $IPBHTML;
}

/* -- bbCodeItem --*/
function bbCodeItem($item="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- category_index --*/
function category_index($categories) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- category_view --*/
function category_view($category, $categories, $items, $pages, $sort, $filter, $siblings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['category_view'] ) )
{
$count_8aafcd8caaa1d1f545e080130142e4ae = is_array($this->functionData['category_view']) ? count($this->functionData['category_view']) : 0;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['category'] = $category;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['categories'] = $categories;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['items'] = $items;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['pages'] = $pages;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['sort'] = $sort;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['filter'] = $filter;
$this->functionData['category_view'][$count_8aafcd8caaa1d1f545e080130142e4ae]['siblings'] = $siblings;
}

if ( ! isset( $this->registry->templateStriping['items'] ) ) {
$this->registry->templateStriping['items'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<script type='text/javascript' src='{$this->settings['js_base_url']}js/ips.classifieds_mobile.js'></script>
<div class='master_list' id='category_view'>
" . ((count($categories)) ? ("
	<div class='controls' id='cat-dropdown'>
		<div class='buttons'>
		<span class='button'>{$category['name']}</span>
		</div>
	</div>	
") : ("")) . "
					<div class=\"category_list\" id=\"category_menu\">
					<ul>
          				".$this->__f__81552812c6175766fd1c9a2958faf57c($category,$categories,$items,$pages,$sort,$filter,$siblings)."        			</ul>
				</div>        			
        	<script type=\"text/javascript\">
				/* Prevent flash of header */
				document.getElementById('category_menu').style.display = 'none';
			</script>
	<div >
				<h3 class=\"title\">{$this->lang->words['cfds_items_in']} {$category['name']}</h3>
	</div>
        			
            " . ((count($items)) ? ("                 ".$this->__f__ee30c8829fd84e58ca4728c27d1c662c($category,$categories,$items,$pages,$sort,$filter,$siblings)."                ") : ("
	                <div class='no_messages'>
						{$this->lang->words['cfds_no_items']}
					</div>
            ")) . "
<div class='controls'>
	<div class='buttons'>
		{$pages}
	</div>
</div>

</div>";
return $IPBHTML;
}


function __f__81552812c6175766fd1c9a2958faf57c($category, $categories, $items, $pages, $sort, $filter, $siblings)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories as $category )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				            <li class='row touch-row'>
				            
                		<span class='item_count' data-tooltip=\"" . $this->registry->getClass('class_localization')->formatNumber( $category['item_count'] ) . " {$this->lang->words['cfds_active_adverts']}\">
							" . $this->registry->getClass('class_localization')->formatNumber( $category['item_count'] ) . "
						</span>
										            
				            <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order={$sort['order']}&amp;filter={$filter}", "publicWithApp",'' ), "{$category['seo_title']}", "view_category" ) . "\" data-tooltip=\"{$category['name']}\" class='title'>" . IPSText::truncate($category['name'], 35) . "</a>

            				</li>
          				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__ee30c8829fd84e58ca4728c27d1c662c($category, $categories, $items, $pages, $sort, $filter, $siblings)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
                    " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'item_row' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->item_row($item) : '' ) . "
                
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- checkboxFormField --*/
function checkboxFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- chooseCategory --*/
function chooseCategory($form, $error='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- delete_item_form --*/
function delete_item_form($item, $form) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- delete_question_form --*/
function delete_question_form($question, $form) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- dropdownFormField --*/
function dropdownFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- inputFormField --*/
function inputFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- item_attachments --*/
function item_attachments($attachments, $item) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- item_row --*/
function item_row($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['item_row'] ) )
{
$count_7e4fa9d8edbb03088b010071b8c90b11 = is_array($this->functionData['item_row']) ? count($this->functionData['item_row']) : 0;
$this->functionData['item_row'][$count_7e4fa9d8edbb03088b010071b8c90b11]['item'] = $item;
}
$IPBHTML .= "<div class='row touch-row' id=\"item-{$item['item_id']}\">
	<div class='icon'>
						" . (($item['thumb_location']) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"35\" height=\"35\" /></a>
						") : ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src='{style_images_url}/classifieds/noimage.png' width=\"35\" height=\"35\" /></a>
						")) . "
	</div>
	<div class='rowContent'>
	
		<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}\" title='' class='title'>" . IPSText::truncate($item['name'], 28) . "</a>
		<br />
		<span class='desc'>
			" . (($item['advert_type'] == 'wanted') ? (" <span class='ipsBadge ipsBadge_orange right'>{$this->lang->words['cfds_wanted']}</span> &middot; ") : ("")) . "
			" . (($item['advert_type'] == 'exchange') ? (" <span class='ipsBadge ipsBadge_purple right'>{$this->lang->words['cfds_exchange']}</span> &middot; ") : ("")) . "
			" . (($item['price'] != '0.00') ? (" " . ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], false ) . "") : ("" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_free']}") : ("{$this->lang->words['cfds_wanted_noprice']}")) . "")) . "
		</span>
	</div>
</div>";
return $IPBHTML;
}

/* -- item_view --*/
function item_view($item, $seller, $attachments, $questions, $watched) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['item_view'] ) )
{
$count_316eb990a090e7a3d66ca0aee37c6764 = is_array($this->functionData['item_view']) ? count($this->functionData['item_view']) : 0;
$this->functionData['item_view'][$count_316eb990a090e7a3d66ca0aee37c6764]['item'] = $item;
$this->functionData['item_view'][$count_316eb990a090e7a3d66ca0aee37c6764]['seller'] = $seller;
$this->functionData['item_view'][$count_316eb990a090e7a3d66ca0aee37c6764]['attachments'] = $attachments;
$this->functionData['item_view'][$count_316eb990a090e7a3d66ca0aee37c6764]['questions'] = $questions;
$this->functionData['item_view'][$count_316eb990a090e7a3d66ca0aee37c6764]['watched'] = $watched;
}
$IPBHTML .= "<h2>
					" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_sale']}") : ("")) . "" . (($item['advert_type'] == 'wanted') ? ("{$this->lang->words['cfds_wanted']}") : ("")) . "" . (($item['advert_type'] == 'exchange') ? ("{$this->lang->words['cfds_exchange']}") : ("")) . " &middot; " . IPSText::truncate( $item['name'], 45 ) . "
	</h2>
	<div id='item_view'>                        	              
                " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'basic_item_info' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->basic_item_info($item, $seller) : '' ) . "                                       
					<div id=\"panel_overview\" class=\"panel\">
	                    <div class='clear'>" . (($item['thumb_location']) ? ("
							<img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" class='cfdsthumb' />
						") : ("")) . " {$item['description']} </div>
						
					</div>
					
					" . ((!empty($item['fields'][0]['fields'])) ? ("".$this->__f__fd55efec7fe0a0aa7db25f4489ba34d8($item,$seller,$attachments,$questions,$watched)."					") : ("")) . "
             <br class='clear' />   
</div>";
return $IPBHTML;
}


function __f__e229b4804d9f183d61ad8cb18961ad76($item, $seller, $attachments, $questions, $watched,$group='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $group['fields'] as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							            
									<li>{$field['title']} &middot; " . (($field['type'] == 'checkbox') ? ("" . (($field['value'] == '1') ? ("{$this->lang->words['cfds_yes']}
					                    ") : ("
					                    {$this->lang->words['cfds_no']}")) . "") : ("
					                     {$field['value']}
					                ")) . "
							        </li>
					                
					            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__fd55efec7fe0a0aa7db25f4489ba34d8($item, $seller, $attachments, $questions, $watched)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['fields'] as $group )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					        " . ((!empty($group['fields'])) ? ("
							        <h3 class=\"bar altbar\">{$group['name']}</h3>
							        <div class='panel'>
							        <ul class=\"ipsList_data clearfix\">
					            ".$this->__f__e229b4804d9f183d61ad8cb18961ad76($item,$seller,$attachments,$questions,$watched,$group)." 
								</ul>
								</div>
					        ") : ("")) . "
					      
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- listing_form --*/
function listing_form($item, $form, $type, $editor, $fields, $post_key, $packages, $category) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- listingPrice --*/
function listingPrice($price) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- moderateSelectCategory --*/
function moderateSelectCategory($categories) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- profileBlock --*/
function profileBlock($items=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- question_form --*/
function question_form($item, $editor, $post_key) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- radioFormField --*/
function radioFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- rateCard --*/
function rateCard($package) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- renewal_form --*/
function renewal_form($item, $form) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- search_row --*/
function search_row($item) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- seller_info --*/
function seller_info($seller, $item) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- textareaFormField --*/
function textareaFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- uploadForm --*/
function uploadForm($post_key="",$type="",$stats=array(),$id=0) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>