<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:27:58 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_classifieds_manage_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['item_row'] = array('manageitemopen','catssthumb','featuredbadge','typebadge','hasDescription');
$this->_funcHooks['items'] = array('items');
$this->_funcHooks['menu'] = array('activeActive','expiredActive');


}

/* -- item_row --*/
function item_row($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds_manage', $this->_funcHooks['item_row'] ) )
{
$count_5bd108480c3241334872f516ae342f8d = is_array($this->functionData['item_row']) ? count($this->functionData['item_row']) : 0;
$this->functionData['item_row'][$count_5bd108480c3241334872f516ae342f8d]['item'] = $item;
}
$IPBHTML .= "<div class='cfds_category_row " .  IPSLib::next( $this->registry->templateStriping["items"] ) . "" . ((!$item['open']) ? (" moderated") : ("")) . "' id='itemrow_{$item['item_id']}'>
						" . (($item['thumb_location']) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						") : ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src='{style_images_url}/classifieds/noimage.png' width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						")) . "
						
						<div class='item_info right'>
								<p class='ipsType_small'>
								    {$this->lang->words['cfds_sort_views']} - {$item['views']}
								</p>						
							" . (($item['expired'] == 0) ? ("
								<p class='ipsType_small'>
									{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "
								</p>
							") : ("" . (($item['package_info']['max_renewals'] > $item['renewals']) ? ("
	                                    <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=listing&amp;do=renew&amp;item_id={$item['item_id']}", "public",'' ), "", "" ) . "' class=\"ipsButton_secondary\">{$this->lang->words['cfds_renew']}</a>
	                            
	                            ") : ("
	                                {$this->lang->words['cfds_expired']}
	                            ")) . "")) . "	                            
										
						</div>			
						
						<h3 class='ipsType_subtitle'>
																
								<span class='ipsBadge ipsBadge_green priceBadge'>
										    " . ipsRegistry::getClass('class_localization')->echo( $item['price'] ) . "
								</span>
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'>" . IPSText::truncate( $item['name'], 40) . "</a>
						</h3>
						<span class='cat_name'> {$this->lang->words['cfds_in']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_category&amp;category_id={$item['category_id']}", "publicWithApp",'' ), "{$item['catseo']}", "view_category" ) . "\">{$item['catname']}</a></span>
						" . (($item['featured'] == 1) ? (" <span class='ipsBadge ipsBadge_green right' style='margin-left:4px;'>{$this->lang->words['cfds_featured']}</span>") : ("")) . "
						" . (($item['show_badge'] == 1) ? ("<span class='ipsBadge ipsBadge_{$item['badge_color']} right'>{$item['advert_type']}</span>") : ("")) . "
						<br />
						
						{$this->lang->words['cfds_by']} " . IPSMember::makeProfileLink($item['member']['members_display_name'], $item['member']['member_id'], $item['member']['members_seo_name']) . "
						
						" . (($item['description']) ? ("
							<br /><br /><span class='desc'>" . IPSText::truncate(strip_tags($item['description']) , $this->settings['classifieds_desc_trunc']) . "</span>
						") : ("")) . "
						<br style=\"clear:both;\" />
					</div>";
return $IPBHTML;
}

/* -- items --*/
function items($items, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds_manage', $this->_funcHooks['items'] ) )
{
$count_88250799adfde4a5bfad9d452821fe11 = is_array($this->functionData['items']) ? count($this->functionData['items']) : 0;
$this->functionData['items'][$count_88250799adfde4a5bfad9d452821fe11]['items'] = $items;
$this->functionData['items'][$count_88250799adfde4a5bfad9d452821fe11]['pages'] = $pages;
}

if ( ! isset( $this->registry->templateStriping['items'] ) ) {
$this->registry->templateStriping['items'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<ul class='topic_buttons'>
<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=listing&amp;do=cat", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_add_item']}\" class='ipsButton'><img src='{style_images_url}/add.png' /> {$this->lang->words['cfds_add_item']}</a></li>
</ul>
<h1 class='ipsType_pagetitle ipsPad'>{$this->lang->words['cfds_my_classifieds']}</h1>
<div class='ipsBox'>
	<div class='ipsLayout ipsLayout_withleft ipsLayout_smallleft ipsVerticalTabbed'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds_manage'), 'menu' ) ? $this->registry->getClass('output')->getTemplate('classifieds_manage')->menu() : '' ) . "		
		<div class='ipsLayout_content ipsVerticalTabbed_content ipsBox_container'>
		<div class='ipsPad'>{$pages}</div>
			<div class='ipsPad clear'>
			
				<div id='cfds_category' class='ipsBox_container'>
		            " . ((count($items)) ? (" 		                ".$this->__f__a6bb9b889e3d0d4283006aef97079b9e($items,$pages)."		                ") : ("
			                <div class='no_messages'>
								{$this->lang->words['cfds_no_items']}
							</div>
		            ")) . "
		        </div>
	        </div>
		</div>
	</div>
	<br class='clear' />
</div>";
return $IPBHTML;
}


function __f__a6bb9b889e3d0d4283006aef97079b9e($items, $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "	
		                    " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds_manage'), 'item_row' ) ? $this->registry->getClass('output')->getTemplate('classifieds_manage')->item_row($item) : '' ) . "	
		                
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- menu --*/
function menu() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds_manage', $this->_funcHooks['menu'] ) )
{
$count_d317334c96f5068e9135abf0dfe8d752 = is_array($this->functionData['menu']) ? count($this->functionData['menu']) : 0;
}
$IPBHTML .= "<div class='ipsLayout_left ipsVerticalTabbed_tabs'>
			<ul>
				<li" . (($this->request['do'] == 'active' || $this->request['do'] == '') ? (" class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=manage&amp;do=active", "public",'' ), "", "" ) . "'>{$this->lang->words['cfds_active_adverts']}</a></li>
				<li" . (($this->request['do'] == 'expired') ? (" class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=manage&amp;do=expired", "public",'' ), "", "" ) . "'>{$this->lang->words['cfds_expired_adverts']}</a></li>
			</ul>			
		</div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>