<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:27:58 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ipseo_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- metaEditor --*/
function metaEditor($tags, $url) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox ipsPad'>
	
	<h2 class='ipsType_subtitle left'>{$this->lang->words['meta_editor_title']}</h2>
	
	<span class='right'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=ipseo&module=meta&section=meta&do=end", "public",'' ), "", "" ) . "' class='ipsButton_secondary'>{$this->lang->words['meta_editor_done']}</a></span>
	
	<br class='clear' />
	
	<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=ipseo&module=meta&section=meta&do=save", "public",'' ), "", "" ) . "' method='post'>
		<input type='hidden' name='url' value='{$url}' />
		<table class='ipb_table'>
			<tr>
				<th>{$this->lang->words['meta_tag_title']}<br /><span class='desc'>{$this->lang->words['meta_tag_title_desc']}</span></th>
				<th>{$this->lang->words['meta_tag_content']}</th>
			</tr>
			".$this->__f__c4b4e89b5bc204631a91ef85ef6306d3($tags,$url)."			<tr>
				<td><input name='meta-tags-title[]' /></td>
				<td><input name='meta-tags-content[]' /></td>
			</tr>
			<tr>
				<td colspan='2'>
					<input type='submit' class='ipsButton_secondary clickable' value='{$this->lang->words['meta_save']}' />
				</td>
			</tr>
		</table>
	</form>
	
</div>";
return $IPBHTML;
}


function __f__c4b4e89b5bc204631a91ef85ef6306d3($tags, $url)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags as $k => $v )
	{
		
$_metaTagId++;

		$__iteratorCount++;
		$_ips___x_retval .= "
				" . (($k != 'identifier-url') ? ("
					<tr>
						<td><input name='meta-tags-title[]' value='{$k}' /></td>
						<td><input name='meta-tags-content[]' value='{$v}' /></td>
					</tr>
									") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>