<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:27:58 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_classifieds_hooks_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['randomAd'] = array('typebadge');
$this->_funcHooks['sidebar_hook_latest'] = array('latest_classifieds_hook','latestclassifieds');


}

/* -- manage_link --*/
function manage_link($url) {
$IPBHTML = "";
$IPBHTML .= "<li><a href='{$url}'>{$this->lang->words['cfds_manage_classifieds']}</a></li>";
return $IPBHTML;
}

/* -- randomAd --*/
function randomAd($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds_hooks', $this->_funcHooks['randomAd'] ) )
{
$count_903b46b7a476cc69f38fc1e34be7432e = is_array($this->functionData['randomAd']) ? count($this->functionData['randomAd']) : 0;
$this->functionData['randomAd'][$count_903b46b7a476cc69f38fc1e34be7432e]['item'] = $item;
}
$IPBHTML .= "<br />
<h3 class='bar'>{$this->lang->words['cfds_random_ad']}</h3>
  <div class=\"ipsBox_container ipsPad\" style=\"text-align:center;\">
  	
    <h4 class='ipsType_subtitle'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "{$item['seo_title']}", "view_item" ) . "\">{$item['name']}</a></h4>
    <p class='ipsType'>
    " . (($item['show_badge'] == 1) ? ("<span class='ipsBadge ipsBadge_{$item['badge_color']}'>{$item['advert_type']}</span>") : ("")) . "
	{$this->lang->words['cfds_by']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$item['seller']['member_id']}", "public",'' ), "{$item['seller']['members_seo_name']}", "showuser" ) . "'>{$item['seller']['members_display_name']}</a>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($item['seller']['member_id'],$item['seller']['members_seo_name']) : '' ) . "</p>
    <div style='position: relative; margin: 4px 0 12px 0;'>
	 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "{$item['seo_title']}", "view_item" ) . "\">" . (($item['thumb_location']) ? (" <img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"100\" height=\"100\" class=\"cfdsthumb\" style=\"float:none; margin-top:4px;\" />
                ") : ("
                <img src='{style_images_url}/classifieds/noimage.png' class=\"cfdsthumb\" width=\"100\" height=\"100\" style=\"float:none; margin-top:4px;\" /> ")) . "</a>
						<span class='ipsBadge ipsBadge_green priceBadge_sidebar'>
						" . (($item['price'] != '0.00' || !$item['zero_text']) ? (" " . ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], false ) . "") : ("
                            {$item['zero_text']}                         
                        ")) . "
						</span>
                    </div>
            <p class='ipsType_small'>{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "</p>
                
    </div>";
return $IPBHTML;
}

/* -- sidebar_hook_latest --*/
function sidebar_hook_latest($items) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds_hooks', $this->_funcHooks['sidebar_hook_latest'] ) )
{
$count_b541d5c6f04f0b9f0ae12e372cae99cc = is_array($this->functionData['sidebar_hook_latest']) ? count($this->functionData['sidebar_hook_latest']) : 0;
$this->functionData['sidebar_hook_latest'][$count_b541d5c6f04f0b9f0ae12e372cae99cc]['items'] = $items;
}

if ( ! isset( $this->registry->templateStriping['latest_classifieds'] ) ) {
$this->registry->templateStriping['latest_classifieds'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='ipsSideBlock clearfix'>
		<h3><img src='{$this->settings['img_url']}/classifieds/merchant.png' alt='{$this->lang->words['icon']}' /> {$this->lang->words['cfds_latest']}</h3>
		<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
			" . ((is_array( $items ) && count( $items )) ? ("
								".$this->__f__16e2f0d36549a8795fff5721d55743cb($items)."			") : ("
				<li>{$this->lang->words['cfds_no_recent']}</li>
			")) . "
		</ul>
		</div>
                <p style='margin:5px 0 5px 5px;'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=listing&amp;do=cat", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_add_item']}\"><img src='{style_images_url}/add.png' /> {$this->lang->words['cfds_add_item']}</a></p>
	</div>";
return $IPBHTML;
}


function __f__16e2f0d36549a8795fff5721d55743cb($items)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["latest_classifieds"] ) . "'>
							" . (($item['member']['member_id']) ? ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$item['member']['member_id']}", "public",'' ), "{$item['member']['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink'>
			") : ("")) . "
			<img src='{$item['member']['pp_thumb_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$item['member']['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_mini left' />
			" . (($item['member']['member_id']) ? ("
				</a>
			") : ("")) . "
			<div class='list_content'>
				" . (($item['advert_type'] == 'wanted') ? ("<span>{$this->lang->words['cfds_wanted']} </span>") : ("")) . "<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' rel='bookmark' title='{$this->lang->words['cfds_view_classified']}' class='ipsType_small'>{$item['name']}</a>
				{$this->lang->words['cfds_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$item['member']['member_id']}", "public",'' ), "{$item['member']['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$item['member']['members_display_name']}</a>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'user_popup' ) ? $this->registry->getClass('output')->getTemplate('global')->user_popup($item['member']['member_id'], $item['member']['members_seo_name']) : '' ) . "</address><br />
				<span class='date'>{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "</span>
				</div>
				</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>