<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Mon, 28 Sep 2015 13:27:58 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_classifieds_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['answer_form'] = array('forsaleorwanted');
$this->_funcHooks['basic_item_info'] = array('contactseller','hasShareLinks');
$this->_funcHooks['bbCodeItem'] = array('smthumb','typebadge');
$this->_funcHooks['category_view'] = array('sub_categories','siblings','filterloop','filterloop','items','categorytest','siblingtest','listitem','stopwatching','watchismember','categorydescription');
$this->_funcHooks['chooseCategory'] = array('hasError');
$this->_funcHooks['item_row'] = array('catitemopen','catssthumb','featuredbadge','typebadge','hasDescription');
$this->_funcHooks['item_view'] = array('yesno','fieldtypetest','fieldinnerloop','groupname','grouploop','questionloop','stopwatching','watchismember','edititem','askquestion','canReportItem');
$this->_funcHooks['listing_form'] = array('fieldinnerloop','groupname','grouploop','typeloop','packages','AddOrEdit','CategoryChange','upload_form_check','cs_precedes','cs_follows','packages_check');
$this->_funcHooks['profileBlock'] = array('readunread','profilethumb','featuredbadge','typebadge','hasDescription');
$this->_funcHooks['question_form'] = array('forsaleorwanted');
$this->_funcHooks['renewal_form'] = array('cs_precedes','cs_follows');
$this->_funcHooks['search_row'] = array('forsaleorwanted');
$this->_funcHooks['seller_info'] = array('hasPhoto','authorspammerinner','authorspammer','isFriend','noFriendYourself','dnameHistory','RepPositive','RepNegative','RepZero','ourReputation');
$this->_funcHooks['uploadForm'] = array('flashuploadhelp');


}

/* -- answer_form --*/
function answer_form($item, $question, $editor, $post_key) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['answer_form'] ) )
{
$count_765af0134e35480d70a453c8a03b74d8 = is_array($this->functionData['answer_form']) ? count($this->functionData['answer_form']) : 0;
$this->functionData['answer_form'][$count_765af0134e35480d70a453c8a03b74d8]['item'] = $item;
$this->functionData['answer_form'][$count_765af0134e35480d70a453c8a03b74d8]['question'] = $question;
$this->functionData['answer_form'][$count_765af0134e35480d70a453c8a03b74d8]['editor'] = $editor;
$this->functionData['answer_form'][$count_765af0134e35480d70a453c8a03b74d8]['post_key'] = $post_key;
}
$IPBHTML .= "<div class=\"ipsLayout\">
      <h3 class=\"maintitle\">{$this->lang->words['cfds_answering_question']}</h3>
	<div class='ipsBox'>
	<h3 class=\"bar altbar\">{$this->lang->words['cfds_item_details']}</h3>
		<div class='ipsBox_container ipsPad'>  
			<p>{$this->lang->words['cfds_name']} - {$item['name']}</p>
			<p>{$this->lang->words['cfds_price']} - " . (($item['price'] != '0.00') ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], true )) . "") : ("" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_free']}") : ("{$this->lang->words['cfds_wanted_noprice']}")) . "")) . "</p>
        </div>
	</div>
	
	<div class='ipsBox'>
	<h3 class=\"bar altbar\">{$this->lang->words['cfds_question']}</h3>
		<div class='ipsBox_container ipsPad'>  
				{$question['question']}
		</div>
	</div>
    
        <form action='{$this->settings['base_url']}app=classifieds&amp;module=questions&amp;do=doanswer' id='mainform' method='post'>
      <input type='hidden' name='question_id' value='{$question['question_id']}' />
      <input type='hidden' name='post_key' value='{$post_key}' />
    <ul class=\"ipsForm ipsForm_horizontal\">
	<div class='ipsBox'>
		<div class='ipsBox_container ipsPad'>
			<li class=\"ipsField\">
	        <label class=\"ipsField_title\" for=\"answer\">{$this->lang->words['cfds_answer']} <span class=\"ipsForm_required\">*</span></label>
	        <div class=\"ipsField_content\">{$editor}</div>
	        </li>
	        <li class=\"ipsField ipsField_checkbox\">
	        <input type=\"checkbox\" name=\"public_answer\" value=\"1\" checked />
	        <div class=\"ipsField_content\">
        		<label for=\"public_answer\">{$this->lang->words['cfds_public_answer']}</label>
        	</div>
            
            </li>
		</div>
	</div>
    </ul>  
    <br class='clear' />
		<fieldset class=\"submit\">
	        <input type=\"submit\" name=\"submit\" value=\"{$this->lang->words['cfds_answer_action']}\" class=\"input_submit\" />
	          " . (($item) ? (" {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
	          ") : ("
	          {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
	          ")) . "
    	</fieldset>
	</form>
</div>";
return $IPBHTML;
}

/* -- basic_item_info --*/
function basic_item_info($item, $seller) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['basic_item_info'] ) )
{
$count_20eb28ac3f50f0d7014bf87827aad07e = is_array($this->functionData['basic_item_info']) ? count($this->functionData['basic_item_info']) : 0;
$this->functionData['basic_item_info'][$count_20eb28ac3f50f0d7014bf87827aad07e]['item'] = $item;
$this->functionData['basic_item_info'][$count_20eb28ac3f50f0d7014bf87827aad07e]['seller'] = $seller;
}
$IPBHTML .= "<h1 class='ipsType_subtitle'>
    				 {$item['name']} <span class='ipsBadge ipsBadge_{$item['badge_color']} right'>{$item['advert_type']}</span>					
    			</h1>
                    <div class=\"price_box rounded\"> {$this->lang->words['cfds_price']} -
                        " . (($item['price'] != '0.00' || !$item['zero_text']) ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], true )) . "") : ("
                            {$item['zero_text']}                         
                        ")) . "
                    </div>
                    <p>{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "</p>
                    
                    
			         " . (($this->memberData['member_id']) ? ("" . ((($seller['member_id'] != $this->memberData['member_id']) AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' )) ? ("
			              <a class='pm_button' id='pm_xxx_{$seller['member_id']}' href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$seller['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['cfds_contact_seller']}' title='{$this->lang->words['cfds_contact_seller']}'><div class=\"purchase_box rounded\">" . $this->registry->getClass('output')->getReplacement("send_msg") . " {$this->lang->words['cfds_contact_seller']}</div></a>
			            ") : ("")) . "") : ("
			        <div class=\"purchase_box rounded\">{$this->lang->words['cfds_sign_in']}</div>
			        ")) . "                   
		            " . (($this->settings['sl_enable']) ? ("
					<div class='ipsPad'>
						" . IPSLib::shareLinks( $item['name'] ) . "
						<br /><br />
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_other'), 'genericFacebookLike' ) ? $this->registry->getClass('output')->getTemplate('global_other')->genericFacebookLike($this->registry->output->buildSEOUrl( 'app=classifieds&amp;module=core&amp;do=view_item&amp;item_id=' . $item['item_id'], 'public', $item['seo_title'] , 'view_item' )) : '' ) . "
					</div>
					") : ("")) . "";
return $IPBHTML;
}

/* -- bbCodeItem --*/
function bbCodeItem($item="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['bbCodeItem'] ) )
{
$count_d40bfcf492c44a1da7307bbb366a64af = is_array($this->functionData['bbCodeItem']) ? count($this->functionData['bbCodeItem']) : 0;
$this->functionData['bbCodeItem'][$count_d40bfcf492c44a1da7307bbb366a64af]['item'] = $item;
}
$IPBHTML .= "<div class='_sharedMediaBbcode'>
	<div class='bbcode_mediaWrap' style='position:relative;'>
		<span class='ipsBadge ipsBadge_green priceBadge' style='position: absolute;top: -6px; left: -4px;font-size: 11px !important;'>
			" . (($item['price'] != '0.00' || !$item['zero_text']) ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], false )) . "") : ("
                  {$item['zero_text']}                         
            ")) . "
		</span>
	
			" . (($item['thumb_location']) ? ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" style=\"padding: 2px;border: 1px solid #e7e7e7;display: inline-block;background: #fff;float: left;\" /></a>
			") : ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src='{$this->settings['img_url']}/classifieds/noimage.png' width=\"75\" height=\"75\" style=\"padding: 2px;border: 1px solid #e7e7e7;display: inline-block;background: #fff;float: left;\" /></a>
			")) . "
		<div class='details' style=\"width:375px;\">
		" . (($item['show_badge'] == 1) ? ("<span class='ipsBadge ipsBadge_{$item['badge_color']} right'>{$item['advert_type']}</span>") : ("")) . "
								
			<h5><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'>{$item['name']}</a></h5> 
			
			<div>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($item['date_added'],"tiny", 0)) . "</div>
			<div>" . IPSText::truncate( $item['description'], 255) . "</div>
		</div>
	</div>
</div>
<br />";
return $IPBHTML;
}

/* -- category_index --*/
function category_index($categories) {
$IPBHTML = "";
$IPBHTML .= "<div class=\"ipsLayout ipsLayout_withleft\">
  <div id=\"intro_text\" class=\"row2 rounded\">
    <p><img src='{style_images_url}/classifieds/merchant.png' /> {$this->lang->words['cfds_intro_text']}</p>
  </div>
  <h3 class=\"maintitle\">{$this->lang->words['cfds_browse']}</h3>
  <div class=\"general_box\" id=\"category_index\">
    " . ((!empty($categories)) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'category_tree' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->category_tree($categories) : '' ) . "") : ("
      {$this->lang->words['cfds_no_cats']} ")) . "
  </div>
</div>";
return $IPBHTML;
}

/* -- category_view --*/
function category_view($category, $categories, $items, $pages, $sort, $filter, $siblings, $types) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['category_view'] ) )
{
$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1 = is_array($this->functionData['category_view']) ? count($this->functionData['category_view']) : 0;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['category'] = $category;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['categories'] = $categories;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['items'] = $items;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['pages'] = $pages;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['sort'] = $sort;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['filter'] = $filter;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['siblings'] = $siblings;
$this->functionData['category_view'][$count_6e1f7f2f6f8d7ae247ca96f1649ee5d1]['types'] = $types;
}

if ( ! isset( $this->registry->templateStriping['items'] ) ) {
$this->registry->templateStriping['items'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<div class=\"ipsLayout ipsLayout_withleft\">
    <div class='ipsLayout_left '><div class='general_box ipsPad'>
    <h1 class='ipsType_pagetitle'>{$category['name']}</h1>
				
			
			" . ((count($categories)) ? ("
				<!-- If this category has subcategories -->
				   <ul class=\"category_list\" id=\"category_menu\">
          				".$this->__f__d3253a85eb772958b58a576e49b148be($category,$categories,$items,$pages,$sort,$filter,$siblings,$types)."        			</ul>
	
			") : ("")) . "
			" . ((count($siblings)) ? ("
				<!-- If this category is a leaf show siblings -->
				   <ul class=\"category_list\" id=\"category_menu\">
          				".$this->__f__06dc9c7e4b644ae1afad689b25298e98($category,$categories,$items,$pages,$sort,$filter,$siblings,$types)."        			</ul>
	
			") : ("")) . "<!--hook.if.skin_classifieds.category_view.siblingtest.post.endif-->
		</div>
    </div>
{$pages}
    <div class='topic_controls'> 
        <ul class='topic_buttons'>
            " . (($this->memberData['g_classifieds_can_list']==1) ? ("" . ((count($categories) == 0) ? ("
	            <li> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=listing&amp;do=add&amp;category_id={$category['category_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_add_item']}\"><img src='{style_images_url}/add.png' /> {$this->lang->words['cfds_add_item']}</a> </li>
	            ") : ("
	            <li> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=listing&amp;do=cat", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_add_item']}\"><img src='{style_images_url}/add.png' /> {$this->lang->words['cfds_add_item']}</a> </li>
	            ")) . "") : ("")) . "
            " . (($this->memberData['member_id']) ? ("" . (($category['watched']) ? ("
                    <li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=subscribe&amp;do=cat_unsubscribe&amp;id={$category['category_id']}", "public",'' ), "", "" ) . "' title=''><img src='{style_images_url}/classifieds/transmit_blue.png'> {$this->lang->words['cfds_unsubscribe_cat']}</a></li>
                    ") : ("
                    <li>
                        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=subscribe&amp;do=cat_subscribe&amp;id={$category['category_id']}", "public",'' ), "", "" ) . "' title=''><img src='{style_images_url}/classifieds/transmit_blue.png'> {$this->lang->words['cfds_subscribe_cat']}</a>
                    </li>
                ")) . "") : ("")) . "
        </ul>
    </div>
    <br />
    " . (($category['description']) ? ("
    	<p class='message unspecific' style=\"clear:none;\">{$category['description']}</p>
    ") : ("")) . "
    <div class='ipsLayout_content'>
        <div class=\"maintitle ipsFilterbar\">
            <a href='#filter_type_menucontent' id='filter_type' class='right ipsType_smaller'>
                " . (($filter == '0' || !$filter ) ? ("{$this->lang->words['cfds_all_advert_types']}") : ("")) . "".$this->__f__e2cbd23e1c393c72a20e69dc7919a098($category,$categories,$items,$pages,$sort,$filter,$siblings,$types)."                <img src='{$this->settings['img_url']}/useropts_arrow.png' />
            </a>
            <span class='ipsType_small'>{$this->lang->words['cfds_sort_by']}</span>&nbsp;&nbsp;
			<ul class='ipsList_inline' style='display:inline;'>			
				<li" . (($sort['key'] == 'date_added') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key=date_added&amp;sort_order={$sort['order']}&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_date']}</a>
				</li>			
				<li" . (($sort['key'] == 'price') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key=price&amp;sort_order={$sort['order']}&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_price']}</a>
				</li>
				<li" . (($sort['key'] == 'date_expiry') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key=date_expiry&amp;sort_order={$sort['order']}&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_timeleft']}</a>
				</li>	
				<li" . (($sort['key'] == 'views') ? (" class='active'") : ("")) . ">
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key=views&amp;sort_order={$sort['order']}&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_views']}</a>
				</li>					
				
			</ul> 
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
				<span class='ipsType_small'>{$this->lang->words['cfds_sort_order']}</span>&nbsp;&nbsp;
				<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
					<li" . (($sort['order'] == 'desc') ? (" class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order=desc&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_desc']}</a>
					</li>
					<li" . (($sort['order'] == 'asc') ? (" class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order=asc&amp;filter={$filter}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_sort_asc']}</a>
					</li>
				</ul>			         
        </div>
        <ul id='filter_type_menucontent' class='ipbmenu_content with_checks' style='display: none'>
            <li" . (($filter == '0' || !$filter ) ? (" class='selected'") : ("")) . ">
                <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order={$sort['order']}&amp;filter=all", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$this->lang->words['cfds_all_advert_types']}</a>
            </li>
            ".$this->__f__41975e37e587b572d23a0d6ba6108695($category,$categories,$items,$pages,$sort,$filter,$siblings,$types)."        </ul>
        <script type='text/javascript'>
            new ipb.Menu( $('filter_type'), $('filter_type_menucontent') );
        </script>
        <div id='cfds_category' class='ipsBox_container'>
            " . ((count($items)) ? ("                 ".$this->__f__85278cb985fff849014fa8718fe6edc9($category,$categories,$items,$pages,$sort,$filter,$siblings,$types)."                ") : ("
	                <div class='no_messages'>
						{$this->lang->words['cfds_no_items']}
					</div>
            ")) . "
        </div>
                
     		" . (($this->memberData['g_classifieds_can_moderate']) ? ("
			<div id='category_mod' class='moderation_bar rounded with_action clear'>
				<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=moderate", "public",'' ), "", "" ) . "' method='post' id='modform'>
				<input type='hidden' name='do' value='multimod' />
				<input type='hidden' name='category_id' value='{$this->request['category_id']}' />
				<input type=\"hidden\" name=\"secure_key\" value=\"{$this->member->form_hash}\" />
				<input type=\"hidden\" value=\"{$this->request['selecteditemids']}\" name=\"selecteditemids\" id=\"selecteditemids\" />
					<select name='doaction' id='doaction' class='input_select'>
						<option value=''>{$this->lang->words['cfds_mod_with_selected']}</option>
						<option value='move'>{$this->lang->words['cfds_mod_move']}</option>
						<option value='del'>{$this->lang->words['cfds_mod_delete']}</option>
						<option value='feature'>{$this->lang->words['cfds_mod_feature']}</option>
						<option value='unfeature'>{$this->lang->words['cfds_mod_unfeature']}</option>
					</select>&nbsp;
					<input type=\"submit\" name=\"gobutton\" value=\"{$this->lang->words['mod_button']}\" class=\"input_submit alt\" id='mod_submit' />
				</form>
			</div>
			<div class='moderation_bar ipsType_small' style='text-align: center;'>
				<a href='#' id='moderator_toggle'><img src='{$this->settings['img_url']}/moderation_cog.png' />&nbsp; {$this->lang->words['cfds_show_mod']}</a>
			</div>
			<script type='text/javascript'>
				ipb.vars['lang_suredelete'] = '{$this->lang->words['cfds_suredelete']}';
				
				$('modform').observe('submit', ipb.classifieds.submitModForm);
				$('category_mod').hide();
				
				$('moderator_toggle').up('div').show().observe('click', function(e){
					Event.stop(e);
					$('moderator_toggle').up('div').hide();
					$('category_mod').show();
				});
			</script>
			") : ("")) . "
		
        
                {$pages}
                <br />
    </div>
    
    
    
</div>
" . $this->registry->getClass('output')->addJSModule("classifieds", "0" ) . "";
return $IPBHTML;
}


function __f__d3253a85eb772958b58a576e49b148be($category, $categories, $items, $pages, $sort, $filter, $siblings, $types)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories as $category )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				            <li>" . (($category['is_read'] == 1) ? ("<img src='{style_images_url}/classifieds/tag_read.png' alt='Category Read' class='menutag' />") : ("<img src='{style_images_url}/classifieds/tag_unread.png' alt='Category Unread' class='menutag' />")) . " <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order={$sort['order']}&amp;filter={$filter}", "publicWithApp",'' ), "{$category['seo_title']}", "view_category" ) . "\" data-tooltip=\"{$category['name']}\">" . IPSText::truncate($category['name'], 20) . "</a>
                		<span class='item_count' data-tooltip=\"" . $this->registry->getClass('class_localization')->formatNumber( $category['item_count'] ) . " {$this->lang->words['cfds_active_adverts']}\">
							" . $this->registry->getClass('class_localization')->formatNumber( $category['item_count'] ) . "
						</span>
            </li>
          				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__06dc9c7e4b644ae1afad689b25298e98($category, $categories, $items, $pages, $sort, $filter, $siblings, $types)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $siblings as $sibling )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				            <li" . (($sibling['category_id'] == $category['category_id']) ? (" class='active'") : ("")) . ">" . (($sibling['is_read'] == 1) ? ("<img src='{style_images_url}/classifieds/tag_read.png' alt='Category Read' class='menutag' />") : ("<img src='{style_images_url}/classifieds/tag_unread.png' alt='Category Unread' class='menutag' />")) . " <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_category&amp;category_id={$sibling['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order={$sort['order']}&amp;filter={$filter}", "publicWithApp",'' ), "{$sibling['seo_title']}", "view_category" ) . "\" data-tooltip=\"{$sibling['name']}\">" . IPSText::truncate($sibling['name'], 20) . "</a>
                		<span class='item_count' data-tooltip=\"" . $this->registry->getClass('class_localization')->formatNumber( $sibling['item_count'] ) . " {$this->lang->words['cfds_active_adverts']}\">
							" . $this->registry->getClass('class_localization')->formatNumber( $sibling['item_count'] ) . "
						</span>
            </li>
          				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e2cbd23e1c393c72a20e69dc7919a098($category, $categories, $items, $pages, $sort, $filter, $siblings, $types)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	if( !is_array($types) ) $types = array($types);
	foreach( $types as $type )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
                " . (($filter == $type['type_id']) ? ("{$type['name']}") : ("")) . "
                
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__41975e37e587b572d23a0d6ba6108695($category, $categories, $items, $pages, $sort, $filter, $siblings, $types)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	if( !is_array($types) ) $types = array($types);
	foreach( $types as $type )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
            <li" . (($filter == $type['type_id']) ? (" class='selected'") : ("")) . ">
                <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$category['category_id']}&amp;sort_key={$sort['key']}&amp;sort_order={$sort['order']}&amp;filter={$type['type_id']}", "public",'' ), "{$category['seo_title']}", "view_category" ) . "'>{$type['name']}</a>
            </li>            
            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__85278cb985fff849014fa8718fe6edc9($category, $categories, $items, $pages, $sort, $filter, $siblings, $types)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
                    " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'item_row' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->item_row($item) : '' ) . "
                
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- checkboxFormField --*/
function checkboxFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<br />
<li class=\"ipsField ipsField_checkbox\">
            <input type=\"checkbox\" name=\"custom-{$field['field_id']}\" value=\"1\" " . (($field['value'] == 1) ? ("checked=\"checked\"") : ("")) . " />
            <div class=\"ipsField_content\"><labelfor=\"custom-{$field['field_id']}\">{$field['title']}" . (($field['required'] == 1) ? (" <span class=\"ipsForm_required\">*</span>") : ("")) . "</label>
            
            " . (($field['description'] != '') ? ("<span class=\"desc\">{$field['description']}</span>") : ("")) . "</div>
          </li>";
return $IPBHTML;
}

/* -- chooseCategory --*/
function chooseCategory($form, $error='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['chooseCategory'] ) )
{
$count_a491229eb272ab7a25a5edc2d529f559 = is_array($this->functionData['chooseCategory']) ? count($this->functionData['chooseCategory']) : 0;
$this->functionData['chooseCategory'][$count_a491229eb272ab7a25a5edc2d529f559]['form'] = $form;
$this->functionData['chooseCategory'][$count_a491229eb272ab7a25a5edc2d529f559]['error'] = $error;
}

if ( ! isset( $this->registry->templateStriping['post_stripe'] ) ) {
$this->registry->templateStriping['post_stripe'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . (($error) ? ("
	<div class='message error'>{$error}</div>
	<br />
") : ("")) . "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "", "" ) . "' method='post'>
	<input type='hidden' name='module' value='listing' />
	<input type='hidden' name='do' value='add' />
	
	<h2 class='maintitle'>{$this->lang->words['cfds_please_select_cat']}</h2>
	<div class='ipsBox'>
		<div class='ipsBox_container ipsPad'>
			<br />
			<ul class='ipsForm_horizontal'>
				<li class='ipsField ipsField_select'>
					<label for='category_id' class='ipsField_title'>{$this->lang->words['cfds_select_cat']}</label>
					<div class='ipsField_content'>
						{$form['category']}
					</div>
				</li>
			</ul>
		</div>
	</div>
	<fieldset class='submit'>
		<input type=\"submit\" name=\"dosubmit\" value=\"{$this->lang->words['cfds_continue']}\" tabindex=\"2\" class=\"input_submit\" accesskey=\"s\" />
		{$this->lang->words['or']}
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "false", "app=classifieds" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
		</fieldset>
</form>";
return $IPBHTML;
}

/* -- delete_item_form --*/
function delete_item_form($item, $form) {
$IPBHTML = "";
$IPBHTML .= "<div class=\"right_column\">
  <div class=\"post_form\">
    <h3 class=\"maintitle\">{$this->lang->words['cfds_deleting']} {$item['name']}</h3>
    <form action='{$this->settings['base_url']}app=classifieds&amp;do={$form['formcode']}' id='mainform' method='post'>
      <input type='hidden' name='item_id' value='{$item['item_id']}' />
      <fieldset>
        <p style=\"padding:1.2em;\">{$this->lang->words['cfds_sure_delete_q']}</p>
      </fieldset>
      <fieldset class=\"submit\">
        <input type=\"submit\" name=\"submit\" value=\"{$form['button']}\" class=\"input_submit\" />
        {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
      </fieldset>
    </form>
  </div>
</div>";
return $IPBHTML;
}

/* -- delete_question_form --*/
function delete_question_form($question, $form) {
$IPBHTML = "";
$IPBHTML .= "<div class=\"right_column\">
  <div class=\"post_form\">
    <h3 class=\"maintitle\">{$this->lang->words['cfds_deleting']} Question</h3>
    <form action='{$this->settings['base_url']}app=classifieds&amp;module=questions&amp;do={$form['formcode']}' id='mainform' method='post'>
      <input type='hidden' name='question_id' value='{$question['question_id']}' />
      <fieldset>
        <p style=\"padding:1.2em;\">{$this->lang->words['cfds_sure_delete_question_q']}</p>
      </fieldset>
      <fieldset class=\"submit\">
        <input type=\"submit\" name=\"submit\" value=\"{$form['button']}\" class=\"input_submit\" />
        {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "do=view_item&amp;item_id={$question['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
      </fieldset>
    </form>
  </div>
</div>";
return $IPBHTML;
}

/* -- dropdownFormField --*/
function dropdownFormField($field) {
$IPBHTML = "";
$IPBHTML .= "" . ((!empty($field['options'])) ? ("<li class=\"ipsField ipsField_select\">
            <label class=\"ipsField_title\" for=\"custom-{$field['field_id']}\">{$field['title']}" . (($field['required'] == 1) ? (" <span class=\"ipsForm_required\">*</span>") : ("")) . "</label>
            <div class=\"ipsField_content\"><select name=\"custom-{$field['field_id']}\" id=\"custom-{$field['field_id']}\" class=\"dropdown\">".$this->__f__3de13cc2da54faa645823721b030a00f($field)."</select></div>
</li>") : ("")) . "";
return $IPBHTML;
}


function __f__3de13cc2da54faa645823721b030a00f($field)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $field['options'] as $option )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value=\"{$option}\" " . (($field['value'] == $option) ? ("selected=\"selected\"") : ("")) . ">{$option}</option>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- inputFormField --*/
function inputFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<li class=\"ipsField\">
            <label class=\"ipsField_title\" for=\"custom-{$field['field_id']}\">{$field['title']}" . (($field['required'] == 1) ? (" <span class=\"ipsForm_required\">*</span>") : ("")) . "</label>
            <div class=\"ipsField_content\"><input value=\"{$field['value']}\" name=\"custom-{$field['field_id']}\" maxlength=\"150\" size=\"30\" class=\"input_text\" id=\"custom-{$field['field_id']}\" type=\"text\">
            " . (($field['description'] != '') ? ("<span class=\"desc\">{$field['description']}</span>") : ("")) . "</div>
          </li>";
return $IPBHTML;
}

/* -- item_attachments --*/
function item_attachments($attachments, $item) {
$IPBHTML = "";
$IPBHTML .= "" . (($attachments) ? ("         
			            <div id=\"Carousel\" class=\"carousel\">
			                <div class=\"button navButton previous\" style=\"display:none;\">Back</div>
			                <div class=\"button navButton next\" style=\"display:none;\">More</div>
			                <div class=\"container\">
			                    <div class=\"items\">                  
			                    ".$this->__f__c1b472fac484fde98d7f4051ec1bc519($attachments,$item)."                                                                                       
			                    </div>
			                </div>
			            </div>        
        				" . $this->registry->getClass('output')->addJSModule("classifieds_attachments", "0" ) . "") : ("")) . "";
return $IPBHTML;
}


function __f__c1b472fac484fde98d7f4051ec1bc519($attachments, $item)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $attachments as $attachment )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			                    	<div class=\"item" . (($item['attach_id'] == $attachment['attach_id']) ? (" selected") : ("")) . "\">
			                            <div class=\"key caption\"></div>
			                            <div class=\"icon\">
			                                <img width=75 height=75 src=\"{$this->settings['upload_url']}/{$attachment['thumb_location']}\" />
			                            </div>
			                            <div class=\"picture\">
			                                <a href='{$this->settings['upload_url']}/{$attachment['full_location']}' rel='lightbox[1]'><img id=\"{$attachment['attach_id']}\" width=300 height=300 src=\"{$this->settings['upload_url']}/{$attachment['med_location']}\" /></a>
			                            </div>
			                        </div>                 
			                    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- item_row --*/
function item_row($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['item_row'] ) )
{
$count_be1ba3b4d88e8b855e9046735a0b880d = is_array($this->functionData['item_row']) ? count($this->functionData['item_row']) : 0;
$this->functionData['item_row'][$count_be1ba3b4d88e8b855e9046735a0b880d]['item'] = $item;
}
$IPBHTML .= "<div class='cfds_category_row " .  IPSLib::next( $this->registry->templateStriping["items"] ) . "" . ((!$item['open']) ? (" moderated") : ("")) . "' id='itemrow_{$item['item_id']}'>
						" . (($item['thumb_location']) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						") : ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src='{style_images_url}/classifieds/noimage.png' width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						")) . "
						
						<div class='item_info right'>
							" . (($this->memberData['g_classifieds_can_moderate']) ? ("
								<input type='checkbox' class='input_check topic_mod right' id='item_{$item['item_id']}' />
							") : ("")) . "
							<p class='ipsType_small'>
							    {$this->lang->words['cfds_sort_views']} - {$item['views']}
							</p>	
											
							<p class='ipsType_small'>
								{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "
							</p>
										
						</div>
						" . (($item['featured'] == 1) ? (" <span class='ipsBadge ipsBadge_green right' style='margin-left:4px;'>{$this->lang->words['cfds_featured']}</span>") : ("")) . "
						" . (($item['show_badge'] == 1) ? ("<span class='ipsBadge ipsBadge_{$item['badge_color']} right'>{$item['advert_type']}</span>") : ("")) . "
												
						<h3 class='ipsType_subtitle'>
										
							
						<span class='ipsBadge ipsBadge_green priceBadge'>
						" . (($item['price'] != '0.00' || !$item['zero_text']) ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], false )) . "") : ("
                            {$item['zero_text']}                         
                        ")) . "
						</span>
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'>" . IPSText::truncate( $item['name'], 40) . "</a>
						</h3><br />
						<span class='cat_name'>{$this->lang->words['cfds_in']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=view_category&amp;category_id={$item['category_id']}", "publicWithApp",'' ), "{$item['catseo']}", "view_category" ) . "\">{$item['catname']}</a></span>
						
						{$this->lang->words['cfds_by']} " . IPSMember::makeProfileLink($item['member']['members_display_name'], $item['member']['member_id'], $item['member']['members_seo_name']) . "
						
						" . (($item['description']) ? ("
							<br /><br /><span class='desc'>" . IPSText::truncate(strip_tags($item['description']) , $this->settings['classifieds_desc_trunc']) . "</span>
						") : ("")) . "
						<br style=\"clear:both;\" />
					</div>";
return $IPBHTML;
}

/* -- item_view --*/
function item_view($item, $seller, $attachments, $questions, $watched) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['item_view'] ) )
{
$count_0a56881bd6d872d8ed86c811ed55c061 = is_array($this->functionData['item_view']) ? count($this->functionData['item_view']) : 0;
$this->functionData['item_view'][$count_0a56881bd6d872d8ed86c811ed55c061]['item'] = $item;
$this->functionData['item_view'][$count_0a56881bd6d872d8ed86c811ed55c061]['seller'] = $seller;
$this->functionData['item_view'][$count_0a56881bd6d872d8ed86c811ed55c061]['attachments'] = $attachments;
$this->functionData['item_view'][$count_0a56881bd6d872d8ed86c811ed55c061]['questions'] = $questions;
$this->functionData['item_view'][$count_0a56881bd6d872d8ed86c811ed55c061]['watched'] = $watched;
}

if ( ! isset( $this->registry->templateStriping['questions'] ) ) {
$this->registry->templateStriping['questions'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_lightbox' ) ? $this->registry->getClass('output')->getTemplate('global')->include_lightbox() : '' ) . "
" . $this->registry->getClass('output')->addJSModule("classifieds_tabs", "0" ) . "
<!-- Start Buttons -->
<ul class='topic_buttons'>
    " . (($this->memberData['member_id']) ? ("" . (($watched) ? ("
            <li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=subscribe&amp;do=item_unsubscribe&amp;id={$item['item_id']}", "public",'' ), "", "" ) . "' title=''><img src='{style_images_url}/classifieds/transmit_blue.png'> {$this->lang->words['cfds_unsubscribe_item']}</a></li>
            ") : ("
            <li> <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=subscribe&amp;do=item_subscribe&amp;id={$item['item_id']}", "public",'' ), "", "" ) . "' title=''><img src='{style_images_url}/classifieds/transmit_blue.png'> {$this->lang->words['cfds_subscribe_item']}</a> </li>
        ")) . "") : ("")) . "
    " . ((($this->memberData['g_classifieds_can_open_close'] == 1 && $this->memberData['member_id'] == $item['member_id']) || $this->memberData['g_classifieds_can_moderate'] == 1) ? ("<li>
        " . (($item['open'] == 1) ? (" <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=close_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_close_item']}\"><img src='{style_images_url}/classifieds/close.png' /> {$this->lang->words['cfds_close_item']}</a>
            ") : ("
            <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=open_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_open_item']}\"><img src='{style_images_url}/classifieds/open.png' /> {$this->lang->words['cfds_open_item']}</a> ")) . "
        </li>") : ("")) . "
    " . ((($this->memberData['g_classifieds_can_edit_item'] == 1 && $this->memberData['member_id'] == $item['member_id']) || $this->memberData['g_classifieds_can_moderate'] == 1) ? ("
        <li> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=listing&amp;do=edit&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_edit_item']}\"><img src='{style_images_url}/classifieds/edit.png' /> {$this->lang->words['cfds_edit_item']}</a> </li>
    ") : ("")) . "
    " . (($this->memberData['g_classifieds_can_moderate'] == 1) ? ("
        <li class=\"closed\"> <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=core&amp;do=delete_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_delete_item']}\"><img src='{style_images_url}/classifieds/bin.png' /> {$this->lang->words['cfds_delete_item']}</a> </li>
    ") : ("")) . "
</ul>
<!-- End Buttons -->
<br class='clear' />
<div class='ipsBox'>
<div class=\"ipsLayout ipsLayout_withright\">
<!-- Start Content -->
        <div class='ipsLayout_content ipsBox_container'>
            <div class='ipsPad_double'>
            <!-- Item Head -->
            " . (($attachments) ? ("
            <div style='width:700px;'>
                <!-- Images -->
                <div class='left item_images'>
                    <div id=\"Viewer\">
		            	<div id=\"ViewerData\" class=\"data\"></div>
	        		</div>            
                </div>
                <!-- End Images -->
            	
                <!-- Item Basics -->
                <div class='right cfds_box_right ipsPad_double'>
                
                " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'basic_item_info' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->basic_item_info($item, $seller) : '' ) . "
                    
                    <!-- Begin attachments -->
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'item_attachments' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->item_attachments($attachments, $item) : '' ) . "
                	<!-- End attachments -->
                    
                    </div>
                <!-- End Item Basics -->
            </div>          
            ") : ("
            
                       <div style='width:700px;'>
                            	
                <!-- Item Basics -->
                <div class='ipsPad_double'>
                
                " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'basic_item_info' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->basic_item_info($item, $seller) : '' ) . "
                                       
                    </div>
                <!-- End Item Basics -->
            </div>            
            
            ")) . "
            <!-- End Item Head -->    
                
                <br class='clear' />	
				<script type=\"text/javascript\">
				//<![CDATA[
				Event.observe(window, 'load', loadTabs, false);
				function loadTabs() {
				var tabs = new tabset('tabContainer');
				tabs.autoActivate($('tab_overview'));
				}
				//]]>
				</script>               
                <div id='tabContainer'>
                <ul class='horizontalTabs' id='tabNav'>
	                <li><a href='#overview' id='tab_overview' class='tab active'>{$this->lang->words['cfds_overview']}</a></li>
	                " . ((!empty($item['fields'][0]['fields'])) ? ("<li><a href='#features' id='tab_features' class='tab'>{$this->lang->words['cfds_features']}</a></li>") : ("")) . "
	                <li><a href='#questions' id='tab_questions' class='tab'>{$this->lang->words['cfds_questions']}</a></li>
                </ul>
                <div class='ipsBox_container ipsPad'>
					<div id=\"panel_overview\" class=\"panel\">
	                    <div class='clear'> {$item['description']} </div>
					</div>
					
					<div id=\"panel_features\" class=\"panel\">
						<div class='general_box clearfix'>
						  " . ((!empty($item['fields'][0]['fields'])) ? ("".$this->__f__d4ab365a1c4dde0e78d53c639324e27a($item,$seller,$attachments,$questions,$watched)."						   ") : ("")) . "
					     </div>				    
					</div>
									
					<div id=\"panel_questions\" class=\"panel\">
						" . ((!empty($questions)) ? ("					
						      						      ".$this->__f__50f4ee90b53b8be7ca8425711673d7f9($item,$seller,$attachments,$questions,$watched)."						    ") : ("")) . "" . ((!$this->templateVars['publicQuestions']) ? ("
						            {$this->lang->words['cfds_no_questions']}
						            ") : ("")) . "
						    " . (($this->memberData['member_id'] AND $seller['member_id'] != $this->memberData['member_id'] AND $this->memberData['g_use_pm']) ? ("
						    <ul class=\"topic_buttons\">
						                    <li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=questions&amp;do=ask&amp;item_id={$item['item_id']}", "public",'' ), "", "" ) . "'><img src='{style_images_url}/classifieds/question.png' /> {$this->lang->words['cfds_no_questions_link_text']}</a> </li>
						    </ul>
						    ") : ("")) . "					  
					</div>                   
                <br class='clear' />
                </div>
                </div>
                
            </div>	
            " . (($this->memberData['member_id']) ? ("
			<div class='ipsPad'>				
				<div class='right'>
					<a class='ipsButton_secondary' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=reports&amp;rcom=classifieds&amp;item_id={$item['item_id']}", "public",'' ), "", "" ) . "\">{$this->lang->words['cfds_report']}</a>
				</div>				
			</div>		
			<br /><br />
			") : ("")) . "
        </div>
<!-- End Content -->
<!-- Start Right Column -->
        <div class='ipsLayout_right'>   
            <div class='ipsBox_container'>
                <h3 class ='bar'>{$this->lang->words['cfds_seller_info']}</h3>
                <div>
                	" . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'seller_info' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->seller_info($seller,$item) : '' ) . "
                </div>
                <br class='clear' />
            </div>
        </div>
<!-- End Right Column -->        
        
        <br class='clear' />		
    </div>
</div>";
return $IPBHTML;
}


function __f__44fcb198e2dd9b936e4a44157e8b9ccc($item, $seller, $attachments, $questions, $watched,$group='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $group['fields'] as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								            
										<li>
								                <span class=\"row_title\">{$field['title']}</span>
								                <span class=\"row_data\">" . (($field['type'] == 'checkbox') ? ("" . (($field['value'] == '1') ? ("{$this->lang->words['cfds_yes']}
						                    ") : ("
						                    {$this->lang->words['cfds_no']}")) . "") : ("
						                     {$field['value']}
						                ")) . "</span>
								        </li>
						                
						            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d4ab365a1c4dde0e78d53c639324e27a($item, $seller, $attachments, $questions, $watched)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $item['fields'] as $group )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						        " . ((!empty($group['fields'])) ? ("<h3 class=\"bar\">" . (($group['name']) ? ("{$group['name']}") : ("{$this->lang->words['cfds_global_field_h']}")) . "</h3>
								        <br />
								        <ul class=\"ipsList_data clearfix\">
						            ".$this->__f__44fcb198e2dd9b936e4a44157e8b9ccc($item,$seller,$attachments,$questions,$watched,$group)." 
									</ul>") : ("")) . "
						      
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__50f4ee90b53b8be7ca8425711673d7f9($item, $seller, $attachments, $questions, $watched)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $questions as $question )
	{
		
if ( 1 == 1 )
{
	$this->templateVars['publicQuestions'] = "1";
}
else {$this->templateVars['publicQuestions'] = $this->__default__templateVars['publicQuestions']; }

		$__iteratorCount++;
		$_ips___x_retval .= "
						      
						      " . (($question['asker_id'] == $this->memberData['member_id'] || $seller['member_id'] == $this->memberData['member_id'] || $question['is_public'] == 1) ? ("						            <div class=\"post_block\" style=\"margin: 0 0 6px 0;\">
						          <h3 class='bar'>
						            " . IPSMember::makeProfileLink($question['askerdata']['members_display_name'], $question['askerdata']['member_id'], $question['askerdata']['members_seo_name']) . "" . (($question['answer'] == '') ? ("<span class='ipsType_small'> ({$this->lang->words['cfds_unanswered_question']})</span>") : ("")) . "</h3>
						          <div class=\"question " .  IPSLib::next( $this->registry->templateStriping["questions"] ) . " " . (($question['is_public'] != 1) ? ("moderated") : ("")) . " \">
						          <p>{$this->lang->words['cfds_pre_question']} {$question['question']}</p>
						          " . (($question['answer'] != '') ? ("
						            <p>{$this->lang->words['cfds_pre_answer']} {$question['answer']}</p>
						          ") : ("")) . "
						          						        " . (($seller['member_id'] == $this->memberData['member_id'] || $this->memberData['g_classifieds_can_moderate'] == 1 ) ? ("<ul class='post_controls'>
						            " . (($question['answer'] == '' && $seller['member_id'] == $this->memberData['member_id']) ? ("
						              <li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=questions&amp;do=answer&amp;question_id={$question['question_id']}", "public",'' ), "", "" ) . "\" class='ipsButton_secondary'>{$this->lang->words['cfds_answer_action']}</a></li>
						            ") : ("")) . "
						            <li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=questions&amp;do=delete&amp;question_id={$question['question_id']}", "public",'' ), "", "" ) . "\" class='ipsButton_secondary'>{$this->lang->words['cfds_delete_question']}</a></li>
						          </ul>
						          <br />") : ("")) . "
						        </div>
						    </div>") : ("")) . "
						    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- listing_form --*/
function listing_form($item, $form, $type, $editor, $fields, $post_key, $packages, $category) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['listing_form'] ) )
{
$count_91e41b0828c7e324a1bfb7cbc79daaf5 = is_array($this->functionData['listing_form']) ? count($this->functionData['listing_form']) : 0;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['item'] = $item;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['form'] = $form;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['type'] = $type;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['editor'] = $editor;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['fields'] = $fields;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['post_key'] = $post_key;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['packages'] = $packages;
$this->functionData['listing_form'][$count_91e41b0828c7e324a1bfb7cbc79daaf5]['category'] = $category;
}
$IPBHTML .= "<script type='text/javascript'>
function getCheckedValue(radio) {
	var radioLength = radio.length;
	if(radioLength == undefined)
		if(radio.checked)
			return radio.value;
		else
			return \"0\";
	for(var i = 0; i < radioLength; i++) {
		if(radio[i].checked) {
			return radio[i].value;
		}
	}
	return \"\";
}
	function updatePrice( value )
	{
	
	var packageid = getCheckedValue(document.forms['mainform'].elements['package']);
	
	
	if(packageid == 0 && document.forms['mainform'].elements['package'].value != '') {
	   packageid = document.forms['mainform'].elements['package'].value; 
	}
	
		if(packageid != 0) {
			new Ajax.Request( ipb.vars['base_url'] + \"app=classifieds&module=ajax&section=listing&do=updateprice&secure_key={$this->member->form_hash}\",
			{
				parameters:
		    	{
		    		packageid: packageid,
		    		value: value
		    	},
				onSuccess: function( t )
				{						
				if ( t.responseJSON && t.responseJSON['error'] )
					{
						alert( t.responseJSON['error'] );
					}
					else
					{
								$( 'listing_price_container' ).innerHTML = t.responseText;
								Effect.Pulsate( $('listing_price'), { pulses: 3, duration: 0.5 } );							
					}			
				}
			});
		}
		
	}
</script>
<div class=\"ipsLayout\">
  
    " . (($type == 'add') ? ("
      <h1 class='ipsType_pagetitle'>" . sprintf( $this->lang->words['cfds_listing_new_item_in'], "{$category['name']}" ) . "</h1>
      ") : ("
      <h1 class='ipsType_pagetitle'>{$this->lang->words['cfds_editing']} {$item['name']}</h1>
    ")) . "
    
    <div class=\"ipsBox\">
    <form action='{$this->settings['base_url']}app=classifieds&amp;module=listing&amp;do={$form['formcode']}' id='mainform' method='post'>
      <input type='hidden' name='item_id' value='{$item['item_id']}' />
      <input type='hidden' name='attach_post_key' value='{$post_key}' />
      <input type='hidden' name='category_id' value='{$item['category_id']}' />
     <ul class=\"ipsForm ipsForm_horizontal\"> 
     " . (($type == 'add') ? ("
     <div class='ipsBox_container ipsPad_double'>
			<div class='ipsPad'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=listing&amp;do=cat&amp;id=", "public",'' ), "", "" ) . "' class='input_submit alt'>{$this->lang->words['cfds_change_category']}</a>
			</div>
		</div>
	<br />
	") : ("")) . "
     <div class='ipsBox_container'>
     
        <h3 class=\"bar altbar\">{$this->lang->words['cfds_item_details']}</h3>
        <div class='ipsPad'>
          <li class=\"ipsField\">
            <label class=\"ipsField_title\" for=\"name\">{$this->lang->words['cfds_name']} <span class=\"ipsForm_required\">*</span></label>
            <div class=\"ipsField_content\"><input type=\"text\" tabindex=\"0\" value=\"{$item['name']}\" name=\"name\" maxlength=\"150\" size=\"50\" class=\"input_text\" id=\"name\"/></div>
          </li>                  
        <li class=\"ipsField\">
         <label class=\"ipsField_title\" for=\"description\">{$this->lang->words['cfds_description']} <span class=\"ipsForm_required\">*</span></label>
        <div class=\"ipsField_content\">{$editor}</div>
        </li>
        
        " . (($form['uploadForm']) ? ("
          
            {$form['uploadForm']}
          
          <br />
      ") : ("")) . "
        
       </div>
      </div>  
      <br />
            ".$this->__f__d6553f44d0c85d2f34bc2e876c2f3eaf($item,$form,$type,$editor,$fields,$post_key,$packages,$category)."      <div class='ipsBox_container'>
        <h3 class=\"bar altbar\">{$this->lang->words['cfds_pricing_options']}</h3>
        <div class='ipsPad'>
          <li class=\"ipsField\">
            <label class=\"ipsField_title\" for=\"price\">{$this->lang->words['cfds_price']} <span class=\"ipsForm_required\">*</span></label>           
            <div class=\"ipsField_content\">
            	" . (($this->lang->local_data['p_cs_precedes']) ? (str_ireplace("LS","€",$this->lang->local_data['currency_symbol'])." ") : ("")) . "<input type=\"text\" value=\"{$item['price']}\" name=\"price\" maxlength=\"150\" size=\"10\" class=\"input_text\" id=\"price\" onchange=\"updatePrice(price.value)\"/>" . ((!$this->lang->local_data['p_cs_precedes']) ? (" ".str_ireplace("LS","€",$this->lang->local_data['currency_symbol'])) : ("")) . "
            </div>
          </li>
           <li class=\"ipsField\">
            <label class=\"ipsField_title\" for=\"advert_type\">{$this->lang->words['cfds_advert_type']} <span class=\"ipsForm_required\">*</span></label>
           <div class=\"ipsField_content\">
           ".$this->__f__40e068dc3f46f79a5051b2209e4311ae($item,$form,$type,$editor,$fields,$post_key,$packages,$category)."           </div>
          </li>
        </div>
      </div>
      <br />
      
      " . ((count($packages) > 1) ? ("
      <div class='ipsBox_container'>
        <h3 class=\"bar altbar\">{$this->lang->words['cfds_packages']}</h3>
        <div class='ipsPad'> 
        	<span class=\"ipsForm_required\">*</span> <span class='required'>{$this->lang->words['cfds_required']}</span>
        </div>
        <div class='ipsPad'>        
        ".$this->__f__9ad26640d23e26f0f5a848c5059b22a4($item,$form,$type,$editor,$fields,$post_key,$packages,$category)."        <br class='clear' />
        </div>
        
      </div>
      <br />
      ") : ("
            <input type='hidden' name='package' value='{$packages[0]['package_id']}' />
      ")) . "</ul>
      <div id=\"listing_price_container\">
	  </div>
      <fieldset class=\"submit\">
        <input type=\"submit\" name=\"submit\" value=\"{$form['button']}\" class=\"input_submit\" />
        " . (($item['item_id']) ? (" {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
          ") : ("
          {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>")) . "
      </fieldset>
    </form>
  </div>
</div>
<script type=\"text/javascript\">
var ajaxUrl = ipb.vars['base_url'] + '&app=classifieds&module=ajax&secure_key=' + ipb.vars['secure_hash'] + '&section=listing&do=ratecard';			
ipb.hoverCardRegister.initialize('ratecard',{ 'w' : '400px', 'delay': 750, 'position' : 'auto' , 'ajaxUrl' : ajaxUrl, 'getId': true, 'setIdParam': 'packageid' } );
</script>";
return $IPBHTML;
}


function __f__03cf42cd1064a4cf219b32e74a6bcc5b($item, $form, $type, $editor, $fields, $post_key, $packages, $category,$group='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $group['fields'] as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
            " . (($field['type'] == 'dropdown') ? ("
            " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'dropdownFormField' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->dropdownFormField($field) : '' ) . "
            ") : ("")) . "
            " . (($field['type'] == 'input') ? ("
            " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'inputFormField' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->inputFormField($field) : '' ) . "
            ") : ("")) . "
            " . (($field['type'] == 'radio') ? ("
            " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'radioFormField' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->radioFormField($field) : '' ) . "
            ") : ("")) . "
            " . (($field['type'] == 'checkbox') ? ("
            " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'checkboxFormField' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->checkboxFormField($field) : '' ) . "
            ") : ("")) . "
            " . (($field['type'] == 'textarea') ? ("
            " . ( method_exists( $this->registry->getClass('output')->getTemplate('classifieds'), 'textareaFormField' ) ? $this->registry->getClass('output')->getTemplate('classifieds')->textareaFormField($field) : '' ) . "
            ") : ("")) . "
            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d6553f44d0c85d2f34bc2e876c2f3eaf($item, $form, $type, $editor, $fields, $post_key, $packages, $category)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $fields as $group )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
            " . ((!empty($group['fields'])) ? ("<div class='ipsBox_container'>
            <h3 class=\"bar altbar\">" . (($group['name']) ? ("{$group['name']}") : ("{$this->lang->words['cfds_global_field_h']}")) . "</h3>
            <div class='ipsPad'>
            ".$this->__f__03cf42cd1064a4cf219b32e74a6bcc5b($item,$form,$type,$editor,$fields,$post_key,$packages,$category,$group)."            </div>
            </div>
            <br />") : ("")) . "
            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__40e068dc3f46f79a5051b2209e4311ae($item, $form, $type, $editor, $fields, $post_key, $packages, $category)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	if( !is_array($category['types']) ) $category['types'] = array($types);
	foreach( $category['types'] as $type )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
           <input type=\"radio\" name=\"advert_type\" value=\"{$type['type_id']}\" " . (($item['type_id'] == $type['type_id']) ? ("checked ") : ("")) . "/> {$type['name']}<br />
           
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__9ad26640d23e26f0f5a848c5059b22a4($item, $form, $type, $editor, $fields, $post_key, $packages, $category)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $packages as $package )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
           <li class=\"ipsField\" style=\"float:left;\">
            <input id=\"package_{$package['package_id']}\" type=\"radio\" name=\"package\" value=\"{$package['package_id']}\" onclick=\"updatePrice(price.value)\"/> 
            <a class=\"_hovertrigger\" hovercard-ref=\"ratecard\" hovercard-id=\"{$package['package_id']}\"><img src='{style_images_url}/classifieds/information.png' alt='{$this->lang->words['cfds_rate_card']}' /></a>
            <label class=\"ipsField_title\" for=\"package_{$package['package_id']}\">{$package['name']}</label>
            <span class=\"desc packagedesc\" style=\"clear:left;\">{$package['description']}</span>
          </li>
        
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- listingPrice --*/
function listingPrice($price) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox_container ipsPad_double'>
			<div class='ipsPad' id=\"listing_price\">
			Listing Price 
			<span class='ipsBadge ipsBadge_green' >
			" . (($price != '0.00') ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $price, false )) . "") : ("
            <p>{$this->lang->words['cfds_free']}</p>")) . "
</span>
			</div>
	  </div>
	  <br />";
return $IPBHTML;
}

/* -- moderateSelectCategory --*/
function moderateSelectCategory($categories) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
	<input type='hidden' name='do' value='multimod' />
	<input type='hidden' name='category_id' value='{$this->request['category_id']}' />
	<input type=\"hidden\" value=\"{$this->request['selecteditemids']}\" name=\"selecteditemids\" id=\"selecteditemids\" />
	<input type='hidden' name='doaction' value='move' />
	<input type='hidden' name='secure_key' value='{$this->member->form_hash}' />
	<h2 class='maintitle'>{$this->lang->words['cfds_move_to']}</h2>
	<div class='ipsBox'>
		<div class='ipsBox_container'>
			<h3 class='bar'>{$this->lang->words['cfds_move_to']}</h3>
			<br />
			<ul class='ipsForm_horizontal'>
				<li class='ipsField ipsField_select'>
					<label for='moveto' class='ipsField_title'>{$this->lang->words['cfds_select_cat']}</label>
					<div class='ipsField_content'>
						{$categories}
					</div>
				</li>
			</ul>
		</div>
	</div>
	<p class='submit'>
		<input type=\"submit\" name=\"dosubmit\" value=\"{$this->lang->words['cfds_multimod_submit']}\" tabindex=\"2\" class=\"input_submit\" accesskey=\"s\" />
		{$this->lang->words['or']} 
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "false", "app=classifieds" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</p>
</form>";
return $IPBHTML;
}

/* -- profileBlock --*/
function profileBlock($items=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['profileBlock'] ) )
{
$count_03412bd8e552148670a9d48f317d3699 = is_array($this->functionData['profileBlock']) ? count($this->functionData['profileBlock']) : 0;
$this->functionData['profileBlock'][$count_03412bd8e552148670a9d48f317d3699]['items'] = $items;
}
$IPBHTML .= "<h3 class='maintitle'>{$this->lang->words['cfds_profile_header']}</h3>
<div class='ipsBox'>
	<div class='ipsBox_container'>
		<table class='ipb_table' summary='{$this->lang->words['cfds_profile_header']}'>
			" . ((is_array($items) AND count($items)) ? ("".$this->__f__1c9edd09d1b53a9d02851c9a8a12a6fd($items)."			") : ("")) . "
		</table>
	</div>
</div>";
return $IPBHTML;
}


function __f__1c9edd09d1b53a9d02851c9a8a12a6fd($items=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $items as $item )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<tr class='" . (($item['is_read']) ? (" unread") : ("")) . "' id='item_{$item['item_id']}'>
					<td class='col_f_icon short altrow'>
						" . ((!$item['is_read']) ? ("
							" . $this->registry->getClass('output')->getReplacement("t_unread") . "
						") : ("
							" . $this->registry->getClass('output')->getReplacement("t_read") . "
						")) . "
					</td>
					<td style=\"width:75px;\">
					<div style='position:relative;'>
				    	<span class='ipsBadge ipsBadge_green' style='position: absolute;top: -6px; left: -4px;font-size: 11px !important;'>
					" . (($item['price'] != '0.00' || !$item['zero_text']) ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], false )) . "
                            ") : ("
                            {$item['zero_text']}                         
                        ")) . "
						</span>
						" . (($item['thumb_location']) ? ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						") : ("
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'><img src='{style_images_url}/classifieds/noimage.png' width=\"75\" height=\"75\" class='cfdsthumb' /></a>
						")) . "
						</div>
					</td>
					<td>
					" . (($item['featured'] == 1) ? (" <span class='ipsBadge ipsBadge_green right' style='margin-left:4px;'>{$this->lang->words['cfds_featured']}</span>") : ("")) . "
					" . (($item['show_badge'] == 1) ? ("<span class='ipsBadge ipsBadge_{$item['badge_color']} right'>{$item['advert_type']}</span>") : ("")) . "
					<h3 class='ipsType_subtitle'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "' title='{$item['name']}'>" . IPSText::truncate( $item['name'], 40) . "</a></h3>
<br />
					<span class='cat_name'>{$this->lang->words['cfds_in']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_category&amp;category_id={$item['category_id']}", "public",'' ), "{$item['catseo']}", "view_category" ) . "\">{$item['catname']}</a></span>
					" . (($item['description']) ? ("
							<br /><br /><span class='desc'>" . IPSText::truncate(strip_tags($item['description']) , $this->settings['classifieds_desc_trunc']) . "</span>
						") : ("")) . "
					</td>
					
				</tr>
			 
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- question_form --*/
function question_form($item, $editor, $post_key) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['question_form'] ) )
{
$count_37251720b78ed8090bda37808e9e42f3 = is_array($this->functionData['question_form']) ? count($this->functionData['question_form']) : 0;
$this->functionData['question_form'][$count_37251720b78ed8090bda37808e9e42f3]['item'] = $item;
$this->functionData['question_form'][$count_37251720b78ed8090bda37808e9e42f3]['editor'] = $editor;
$this->functionData['question_form'][$count_37251720b78ed8090bda37808e9e42f3]['post_key'] = $post_key;
}
$IPBHTML .= "<div class=\"ipsLayout\">
      <h3 class=\"maintitle\">{$this->lang->words['cfds_asking_question']}</h3>
	<div class='ipsBox'>
	<h3 class=\"bar altbar\">{$this->lang->words['cfds_item_details']}</h3>
		<div class='ipsBox_container ipsPad'>  
			<p>{$this->lang->words['cfds_name']} - {$item['name']}</p>
			<p>{$this->lang->words['cfds_price']} - " . (($item['price'] != '0.00') ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], true )) . "") : ("" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_free']}") : ("{$this->lang->words['cfds_wanted_noprice']}")) . "")) . "</p>
        </div>
	</div>
    
	<form action='{$this->settings['base_url']}app=classifieds&amp;module=questions&amp;do=doask' id='mainform' method='post'>
    <input type='hidden' name='item_id' value='{$item['item_id']}' />
    <input type='hidden' name='post_key' value='{$post_key}' />
    <ul class=\"ipsForm ipsForm_horizontal\">
	<div class='ipsBox'>
		<div class='ipsBox_container ipsPad'>
			<li class=\"ipsField\">
	        <label class=\"ipsField_title\" for=\"question\">{$this->lang->words['cfds_question']} <span class=\"ipsForm_required\">*</span></label>
	        <div class=\"ipsField_content\">{$editor}</div>
	        </li>
		</div>
	</div>
    </ul>  
		<fieldset class=\"submit\">
	        <input type=\"submit\" name=\"submit\" value=\"{$this->lang->words['cfds_ask_action']}\" class=\"input_submit\" />
	          " . (($item) ? (" {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "do=view_item&amp;item_id={$item['item_id']}", "publicWithApp",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
	          ") : ("
	          {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
	          ")) . "
    	</fieldset>
	</form>
</div>";
return $IPBHTML;
}

/* -- radioFormField --*/
function radioFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<li class=\"ipsField\">
<label class=\"ipsField_title\" for=\"custom-{$field['field_id']}\">{$field['title']}" . (($field['required'] == 1) ? (" <span class=\"ipsForm_required\">*</span></em>") : ("")) . "</label>
<div class=\"ipsField_content\">".$this->__f__e66f2591fb3ff44fa2d6f119b3510d47($field)."" . (($field['description'] != '') ? ("<span class=\"desc\">{$field['description']}</span>") : ("")) . "
</div>
</li>";
return $IPBHTML;
}


function __f__e66f2591fb3ff44fa2d6f119b3510d47($field)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $field['options'] as $option )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <input type=\"radio\" name=\"custom-{$field['field_id']}\" value=\"{$option}\" " . (($field['value'] == $option) ? ("checked=\"checked\"") : ("")) . " /> {$option}<br />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- rateCard --*/
function rateCard($package) {
$IPBHTML = "";

if ( ! isset( $this->registry->templateStriping['rates'] ) ) {
$this->registry->templateStriping['rates'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<div>
	<h3>{$this->lang->words['cfds_rate_card']}</h3>
	<div style='min-height: 60px'>
			<table class='ipb_table'>
			<tr class='header'><th>&gt= {$this->lang->words['cfds_item_value']}</th><th>{$this->lang->words['cfds_base_price']}</th><th>{$this->lang->words['cfds_renewal_price']}</th></tr>
			" . (($package['pricing_format'] == 'value') ? ("".$this->__f__f988257b78512c779d03328fd612d639($package)."			") : ("
			 	<tr class='" .  IPSLib::next( $this->registry->templateStriping["rates"] ) . "'>
				 <td>{$this->lang->words['cfds_all_values']}</td>
				 <td>" . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $package['price'], false )) . "</td>
				 <td>" . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $package['renewal'], false )) . "</td>
				 </tr>
			")) . "
			</table>
	</div>
</div>";
return $IPBHTML;
}


function __f__f988257b78512c779d03328fd612d639($package)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $package['rates'] as $rate )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				 <tr class='" .  IPSLib::next( $this->registry->templateStriping["rates"] ) . "'>
				 <td>" . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $rate['value'], false )) . "</td>
				 <td>" . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $rate['base'], false )) . "</td>
				 <td>" . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $rate['renewal'], false )) . "</td>
				 </tr>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- renewal_form --*/
function renewal_form($item, $form) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['renewal_form'] ) )
{
$count_5eabad04376cb5426f9f0b7aa53d6be3 = is_array($this->functionData['renewal_form']) ? count($this->functionData['renewal_form']) : 0;
$this->functionData['renewal_form'][$count_5eabad04376cb5426f9f0b7aa53d6be3]['item'] = $item;
$this->functionData['renewal_form'][$count_5eabad04376cb5426f9f0b7aa53d6be3]['form'] = $form;
}
$IPBHTML .= "<form action='{$this->settings['base_url']}app=classifieds&amp;module=listing&amp;do={$form['formcode']}' id='mainform' method='post'>
      <input type='hidden' name='item_id' value='{$item['item_id']}' />
		<h2 class=\"maintitle\">{$this->lang->words['cfds_renewing']} {$item['name']}</h2>
  	<div class='ipsBox'>
		<div class='ipsBox_container ipsPad'>
			<br />        
       
        <ul class='ipsForm_horizontal'>
          <li class='ipsField'>
            <label for=\"price\" class='ipsField_title'>{$this->lang->words['cfds_price']} <span class=\"ipsForm_required\">*</span></label>
            <div class='ipsField_content'>
            " . (($this->lang->local_data['p_cs_precedes']) ? (str_ireplace("LS","€",$this->lang->local_data['currency_symbol'])." ") : ("")) . "<input type=\"text\" value=\"{$item['price']}\" name=\"price\" maxlength=\"150\" size=\"10\" class=\"input_text\" id=\"price\"/>" . ((!$this->lang->local_data['p_cs_precedes']) ? (" ".str_ireplace("LS","€",$this->lang->local_data['currency_symbol'])) : ("")) . "
            </div>
          </li>
        </ul>
		</div>
		</div>
      <fieldset class=\"submit\">
        <input type=\"submit\" name=\"submit\" value=\"{$form['button']}\" class=\"input_submit\" />
          {$this->lang->words['cfds_or']} <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cfds_cancel']}\" class=\"cancel\">{$this->lang->words['cfds_cancel']}</a>
      </fieldset>
    </form>";
return $IPBHTML;
}

/* -- search_row --*/
function search_row($item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['search_row'] ) )
{
$count_c93de0c138fd712c3186f71870a24015 = is_array($this->functionData['search_row']) ? count($this->functionData['search_row']) : 0;
$this->functionData['search_row'][$count_c93de0c138fd712c3186f71870a24015]['item'] = $item;
}
$IPBHTML .= "<div class=\"item_row\">
  <div style=\"float:left; margin-right:10px; width:150px;\">
    " . (($item['is_read'] == 1) ? (" <img src='{style_images_url}/classifieds/tag_read.png' alt='{$this->lang->words['item_read']}'/>
      ") : ("
      <img src='{style_images_url}/classifieds/tag_unread.png' alt='{$this->lang->words['item_unread']}'/> ")) . "
    <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "\">" . (($item['thumb_location']) ? ("<img src=\"{$this->settings['upload_url']}/{$item['thumb_location']}\" width=\"75\" height=\"75\" style='margin-left:10px;'/>
      ") : ("
      <img src='{style_images_url}/classifieds/noimage.png' style='margin-left:10px;' />")) . "</a>
  </div>
  <div style=\"float:left;\">
    <h4><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=classifieds&amp;module=core&amp;do=view_item&amp;item_id={$item['item_id']}", "public",'' ), "{$item['seo_title']}", "view_item" ) . "\">{$item['name']}</a><p class=\"desc\">" . IPSText::truncate(strip_tags($item['description']) , $this->settings['classifieds_desc_trunc']) . "</p></h4>
  </div>
  <div style=\"float:right;margin-left:10px; padding-left:10px; border-left: 1px solid #BBB; width:200px;\">
    <p style=\"font-size: 1.2em;\">{$this->lang->words['cfds_price']} - " . (($item['price'] != '0.00') ? (" " . str_ireplace("LS","€",ipsRegistry::getClass('class_localization')->formatMoney( $item['price'], true )) . "") : ("" . (($item['advert_type'] == 'sale') ? ("{$this->lang->words['cfds_free']}") : ("{$this->lang->words['cfds_wanted_noprice']}")) . "")) . "</p>
   <p>{$this->lang->words['cfds_expires']} - " . $this->registry->classifieds->timeUntil( $item['date_expiry'] )  . "</p></div>
</div>";
return $IPBHTML;
}

/* -- seller_info --*/
function seller_info($seller, $item) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['seller_info'] ) )
{
$count_0c9188966766b3156cfee9cf4a06c37c = is_array($this->functionData['seller_info']) ? count($this->functionData['seller_info']) : 0;
$this->functionData['seller_info'][$count_0c9188966766b3156cfee9cf4a06c37c]['seller'] = $seller;
$this->functionData['seller_info'][$count_0c9188966766b3156cfee9cf4a06c37c]['item'] = $item;
}
$IPBHTML .= "<div id='advertiser_overview' style='text-align:center'>
<div>
<div class='ipsPad'>
					" . (($seller['pp_main_photo']) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$seller['member_id']}", "public",'' ), "{$seller['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink'>
							" . IPSMember::buildProfilePhoto($seller, 'full' ) . "
						</a>
					") : ("
						" . IPSMember::buildNoPhoto(0, 'full' ) . "
					")) . "
</div>
<span class='ipsType_subtitle ipsPad'>" . IPSMember::makeProfileLink($seller['members_display_name'], $seller['member_id'], $seller['members_seo_name']) . "</span>
  <ul>
    " . (($seller['spamStatus'] !== NULL && $seller['member_id'] != $this->memberData['member_id']) ? ("" . (($seller['spamStatus'] === TRUE) ? ("
        <li><a href='#' onclick=\"return ipb.global.toggleFlagSpammer({$seller['member_id']}, false)\">" . $this->registry->getClass('output')->getReplacement("spammer_on") . " {$this->lang->words['spm_on']}</a></li>
        ") : ("
        <li><a href='{$this->settings['base_url']}&amp;app=forums&amp;module=moderate&amp;section=moderate&amp;do=setAsSpammer&amp;member_id={$seller['member_id']}&amp;auth_key={$this->member->form_hash}' onclick=\"return ipb.global.toggleFlagSpammer({$seller['member_id']}, true)\">" . $this->registry->getClass('output')->getReplacement("spammer_off") . " {$this->lang->words['spm_off']}</a></li>
      ")) . "") : ("")) . "
    " . (($this->memberData['member_id'] AND $this->memberData['member_id'] != $seller['member_id'] && $this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("<li id='friend_toggle'>
        " . ((IPSMember::checkFriendStatus( $seller['member_id'] )) ? (" <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=remove&amp;member_id={$seller['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'><img src='{$this->settings['img_url']}/user_delete.png' alt='{$this->lang->words['remove_friend']}' /> {$this->lang->words['remove_as_friend']}</a>
          ") : ("
          <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;section=friends&amp;module=profile&amp;do=add&amp;member_id={$seller['member_id']}&amp;secure_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'><img src='{$this->settings['img_url']}/user_add.png' alt='{$this->lang->words['add_friend']}' /> {$this->lang->words['add_me_friend']}</a> ")) . "
      </li>") : ("")) . "
  
    <li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app=classifieds&amp;mid={$seller['member_id']}", "public",'' ), "", "" ) . "'><img src='{style_images_url}/classifieds/merchant.png' /> {$this->lang->words['cfds_more_from_seller']}</a></li>
    " . (($this->memberData['g_mem_info'] && $this->settings['auth_allow_dnames']) ? ("
      <li id='dname_history'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=dname&amp;id={$seller['member_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['view_dname_history']}'>" . $this->registry->getClass('output')->getReplacement("display_name") . " {$this->lang->words['display_name_history']}</a></li>
    ") : ("")) . "
  </ul>
</div>
" . (($this->settings['reputation_enabled'] && $this->settings['reputation_show_profile']) ? ("<div class='ipsPad'>
" . (($seller['pp_reputation_points'] > 0) ? ("
<div class='reputation positive'>
") : ("")) . "
" . (($seller['pp_reputation_points'] < 0) ? ("
<div class='reputation negative'>
  ") : ("")) . "
  " . (($seller['pp_reputation_points'] == 0) ? ("
  <div class='reputation zero'>
    ") : ("")) . "
    <span class='number'>{$this->lang->words['m_reputation']} {$seller['pp_reputation_points']}</span>
     </div>
</div>") : ("")) . "
</div>";
return $IPBHTML;
}

/* -- textareaFormField --*/
function textareaFormField($field) {
$IPBHTML = "";
$IPBHTML .= "<li class=\"ipsField\">
            <label class=\"ipsField_title\" for=\"custom-{$field['field_id']}\">{$field['title']}" . (($field['required'] == 1) ? (" <span class=\"ipsForm_required\">*</span>") : ("")) . "</label>
            <div class=\"ipsField_content\"><textarea name=\"custom-{$field['field_id']}\" id=\"custom-{$field['field_id']}\" rows=\"4\" cols=\"30\">{$option}</textarea>
            " . (($field['description'] != '') ? ("<span class=\"desc\">{$field['description']}</span>") : ("")) . "</div>
            </li>";
return $IPBHTML;
}

/* -- uploadForm --*/
function uploadForm($post_key="",$type="",$stats=array(),$id=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_classifieds', $this->_funcHooks['uploadForm'] ) )
{
$count_d985f79f9cc756f390ec88f17706df20 = is_array($this->functionData['uploadForm']) ? count($this->functionData['uploadForm']) : 0;
$this->functionData['uploadForm'][$count_d985f79f9cc756f390ec88f17706df20]['post_key'] = $post_key;
$this->functionData['uploadForm'][$count_d985f79f9cc756f390ec88f17706df20]['type'] = $type;
$this->functionData['uploadForm'][$count_d985f79f9cc756f390ec88f17706df20]['stats'] = $stats;
$this->functionData['uploadForm'][$count_d985f79f9cc756f390ec88f17706df20]['id'] = $id;
}
$IPBHTML .= "" . (($this->memberData['member_uploader'] == 'flash') ? ("
  <script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/swfupload/swfupload.js'></script>
  <script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/swfupload/plugins/swfupload.swfobject.js'></script>
  <script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/swfupload/plugins/swfupload.cookies.js'></script>
  <script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/swfupload/plugins/swfupload.queue.js'></script>
") : ("")) . "
<script type='text/javascript'>
//<![CDATA[
	ipb.lang['used_space'] = \"" . sprintf( $this->lang->words['used_space_js'], "{$stats['max_single_upload_human']}" ) . "\";
//]]>
</script>
" . $this->registry->getClass('output')->addJSModule("attach", "0" ) . "
<div class='ipsPad'>
	<div id='attach_error_box' class='message error' style='display:none'></div>
	<input type='file' id='nojs_attach_{$id}_1' class='input_upload' name='FILE_UPLOAD' tabindex='1' />
	<input type='file' id='nojs_attach_{$id}_2' class='input_upload' name='FILE_UPLOAD' tabindex='1' />
	
	<ul id='attachments'><li style='display: none'></li></ul>
	
	<div class='attach_controls'>
		<h2 class='ipsType_subtitle'>{$this->lang->words['attach_header']}</h2>
		<span id='buttonPlaceholder'></span>
		<input type='button' id='add_files_attach_{$id}' class='ipsType_small ipsButton_secondary attach_button' value='{$this->lang->words['attach_selected']}' style='display: none; clear: both' tabindex='-1' />
		&nbsp;&nbsp;<span class='desc ipsType_small' id='space_info_attach_{$id}'>" . sprintf( $this->lang->words['used_space'], "{$stats['space_used_human']}", "{$stats['total_space_allowed_human']}", "{$stats['max_single_upload_human']}") . "</span>
		" . ((!IN_ACP) ? ("<p class='desc lighter ipsType_smaller' id='help_msg'>
				" . (($this->memberData['member_uploader'] == 'flash') ? ("
					 {$this->lang->words['trouble_uploading']} <a href='#' data-switch='default' title='{$this->lang->words['switch']}' tabindex='1'>{$this->lang->words['switch_to_basic']}</a>
				") : ("
					<a href='#' data-switch='flash' title='{$this->lang->words['switch']}' tabindex='-1'>{$this->lang->words['switch_to_advanced']}</a>
				")) . "
			</p>") : ("")) . "
	</div>
	
</div>
<script type='text/javascript'>
//<![CDATA[
	// Show the button and info
	$('add_files_attach_{$id}').show();
	$('space_info_attach_{$id}').show();
	var useType = 'simple';
	var uploadURL = ipb.vars['base_url'] + \"app=core&module=attach&section=attach&do=attachiFrame&attach_rel_module={$type}&attach_rel_id={$id}&attach_post_key={$post_key}&attach_id=attach_{$id}&fetch_all=1\";
	if( jimAuld.utils.flashsniffer.meetsMinVersion(9) && ( ipb.vars['swfupload_enabled'] && ipb.vars['use_swf_upload'] ) )
	{
		useType = 'swf';
		var uploadURL = \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&module=attach&section=attach&do=attach_upload_process&attach_rel_module={$type}&attach_rel_id={$id}&attach_post_key={$post_key}", "public",'' ), "", "" ) . "\";
		$('add_files_attach_{$id}').observe('mouseover', function(e){  } );
	}
	ipb.attach.template = \"<li id='ali_[id]' class='attach_row' style='display: none'><div><h4 class='attach_name'>[name]</h4><p class='info'>[info]</p><span class='img_holder'></span><p class='progress_bar'><span style='width: 0%'>0%</span></p><p class='links'><a href='#' class='cancel delete' title='{$this->lang->words['attach_delete_title']}'>{$this->lang->words['attach_delete']}</a></p></div></li>\";
	document.observe('dom:loaded', function(){
		ipb.attach.registerUploader( 'attach_{$id}', useType, 'attachments', {
			'upload_url': uploadURL,
			'attach_rel_module': \"{$type}\",
			'attach_rel_id': \"{$id}\",
			'attach_post_key': \"{$post_key}\",
			'file_size_limit': \"{$stats['max_single_upload']}\"
		} )});
//]]>
</script>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>