<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 28 Sep 2015 13:27:10 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'active_users_detail' => "<strong>%s</strong> members, <strong>%s</strong> guests, <strong>%s</strong> anonymous users",
'active_users_members' => "%s пользователей:",
'active_users_title' => "%s человек просматривают эту страницу",
'add_comment_title' => "Добавить комментарий",
'change_current_status' => "Изменить текущий статус",
'change_status_title' => "Изменить статус",
'click_here_link' => "Нажмите здесь",
'comments_h2' => "Комментарии",
'configure_notifications' => "Опции уведомлений",
'current_status' => "Текущий статус:",
'delete_report' => "Удалить жалобу",
'go_to_section' => "Просмотр",
'invalid_option' => "Invalid Option Selected",
'list_header_comments' => "Комментариев",
'list_header_last_updated' => "Последнее обновление",
'list_header_reports' => "Жалоб",
'list_header_section' => "Секция",
'list_header_title' => "Название",
'list_header_updated_by' => "Последнее сообщение",
'list_title' => "Жалобы",
'main_title' => "Система жалоб",
'mark_status_as' => "Пометить как",
'no_comments_on_report' => "Комментариев пока нет.",
'no_permission_addreport' => "Вы не можете добавить себя в личную беседу.",
'no_reports' => "Нет жалоб для рассмотрения",
'older_than' => "размещенных больше чем",
'only_active_note' => "Сейчас отображаются только активные жалобы",
'posted_prefix' => "Отправлено",
'post_button' => "Опубликовать",
'redirect_delete_report' => "Удаление жалобы",
'redirect_mark_status' => "Изменение статуса жалобы",
'reported_content_summary' => "Жалобы не контент со всего форума",
'reporting_title' => "Название темы:",
'reports_h2' => "Жалобы",
'reports_messenger' => "Личный ящик",
'reports_methods_saved' => "Настройки уведомлений были сохранены",
'reports_no_comment_text' => "Вы не ввели комментарий.",
'reports_no_plugin' => "Система жалоб для данного типа публикаций не настроена.",
'reports_rss_desc' => "Посмотреть новые жалобы",
'report_about_intro' => "Жалоба относится к",
'report_about_pm' => "личному сообщению:",
'report_actions' => "Опции",
'report_actions_mark_optgroup' => "Пометить жалобу как",
'report_ajax_tab_notif_meth' => "Уведомление",
'report_basic_desc' => "Внимание: данная форма не предназначена для связи с администрацией форума, используйте ее только для указания на нарушающие правила форума публикации!",
'report_basic_enter' => "Введите текст жалобы",
'report_basic_submit' => "Отправить жалобу",
'report_basic_title' => "Сообщить о",
'report_basic_url_title' => "Сообщение о",
'report_by' => "Автор:",
'report_cal_msg' => "<b>Enter your report</b>",
'report_cal_page' => "Report this event to a moderator",
'report_cal_title' => "Event Title",
'report_comment_saved' => "Ваш комментарий был успешно добавлен",
'report_emailpm' => "<#MOD_NAME#>, 
Вам было отправлено уведомление от <#USERNAME#> через кнопку «Жалоба». 

------------------------------------------------ 

Ссылка: <#LINK#> 

------------------------------------------------ 

Жалоба: <#REPORT#> 

------------------------------------------------ ",
'report_file_msg' => "<b>Введите жалобу</b><br /><br />Примечание: Модератор будет проинформирован о ссылке на файл.<br /><br />",
'report_file_page' => "Пожаловаться модератору на файл",
'report_file_title' => "Имя файла",
'report_gallery_comment_suffix' => " - комментарий",
'report_gallery_image_suffix' => " - изображение",
'report_join_pm' => "Присоединится к личной переписке",
'report_mem_msg' => "Введите текст жалобы",
'report_mem_page' => "Сообщить о профиле пользователя",
'report_mem_title' => "Пользователь",
'report_msg_msg' => "<b>Жалоба</b><br />Примечание: копия личного сообщения будет включена в жалобу",
'report_msg_page' => "Пожаловаться модератору на сообщение",
'report_msg_title' => "Личное сообщение",
'report_no_title' => "Нет заголовка у жалобы",
'report_option_delete' => "Удалить",
'report_option_prune' => "Очистить от жалоб",
'report_page_title_unknown' => "Нет заголовка",
'report_post_enter' => "Жалоба",
'report_post_title' => "Отправить жалобу модератору на это сообщение",
'report_post_url_title' => "Тема",
'report_prune_1' => "Удалить отчеты старше, чем",
'report_prune_2' => "дней назад",
'report_prune_days_box' => "дней назад",
'report_prune_message_done' => "Удаление жалоб",
'report_prune_message_none' => "По заданному критерию жалоб не найдено",
'report_reply' => "<#MOD_NAME#>,

<#COMMENTER#> оставил комментарий на жалобу, к которой у вас есть доступ через центр жалоб.

------------------------------------------------

Жалоба на публикацию: <#LINK#>
Ссылка на саму жалобу: <#REPORTLINK#>

------------------------------------------------
Комментарий:

<#COMMENT#>

------------------------------------------------",
'report_section_title_cal' => "Calendar Event",
'report_section_title_mem' => "Профиль пользователя",
'report_section_title_msg' => "Личное сообщение",
'report_section_title_site_downloads' => "Файловый архив",
'report_section_title_site_gallery' => "Site Gallery",
'report_sending' => "Отправка жалобы",
'report_settings_by_alert' => "<b>Notification by Board Alert?</b><br />Receive a notification through a board alert when a report is received. You will see this alert while browsing the forums, and you don't have to fill up your private message box.",
'report_settings_by_email' => "Notification by Email?",
'report_settings_by_pm' => "Notification by Private Message?",
'report_settings_options' => "Notifications",
'report_settings_pm_desc' => "Receive a notification through private message when a report is received.",
'report_settings_save' => "Save",
'report_updated' => "Отправлено: ",
'report_view_reported' => "Посмотреть содержимое",
'rss_feed_title' => "Уведомления о жалобах",
'r_go' => "Ок",
'r_with_selected' => "С выбранными жалобами:",
'select_all_reports' => "Отметить все жалобы",
'status' => "Статус",
'subject_report' => "<a href='%s'>%s</a> оставил <a href='%s'>жалобу</a> на <a href='%s'>следующее</a>",
'subject_reportreply' => "<a href='%s'>%s</a> <a href='%s'>прокомментировал</a> <a href='%s'>публикацию с жалобой</a> ",
'subject_report_guest' => "%s has <a href='%s'>reported</a> <a href='%s'>something</a>",
'to_view_allrep' => "для просмотра всех жалоб",
'view_content' => "Посмотреть содержимое",
'view_member' => "Просмотр профиля",
'view_report' => "Просмотр",
'with_selected' => "with selected",
 ); 
