<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 28 Sep 2015 13:27:10 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'fave_title' => "%s",
'freq_daily' => "Ежедневно",
'freq_immediate' => "Немедленно",
'freq_offline' => "Только, когда не в онлайне",
'freq_weekly' => "Еженедельно",
'label_anon' => "%s анонимных",
'label_anon_desc' => "Не показывать меня в выборке",
'label_freq' => "Частота",
'label_notify' => "Получать уведомление",
'likeadded' => "Добавлено:",
'likedby' => "Следят",
'pg_no_longer_following' => "You are no longer following this item",
'pg_unfollow_confirm' => "Unfollow This Item Now",
'pg_unfollow_text' => "<strong>%s</strong>, you have elected to unfollow the item <a href='%s'>%s</a>.<br />If you unfollow, you will no longer receive notifcations when this item is updated.",
'pg_unfollow_title' => "Unfollow Item",
'pg_unlike_done' => "Item unfollowed successfully",
 ); 
