<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 28 Sep 2015 13:27:13 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'forum_leaders' => "Администрация",
'goto_profile' => "Перейти к профилю",
'go_button' => "OK",
'leader_admins' => "Администраторы",
'leader_all_forums' => "Все форумы",
'leader_forums' => "Форумы",
'leader_global' => "Супермодераторы",
'leader_group' => "Group",
'leader_last_seen' => "Last Active",
'leader_location' => "Последнее действие",
'leader_mods' => "Модераторы",
'leader_name' => "Имя пользователя",
'member' => "Имя пользователя",
'member_joined' => "Регистрация",
'member_percent' => "% сегодняшних сообщений",
'member_posts' => "Всего сообщений",
'member_today' => "Сообщений сегодня",
'm_online' => "Online",
'notopic_attach' => "Не удалось загрузить прикрепленные файлы для запрашиваемой темы",
'no_forums' => "Посмотреть форумы (%s всего)",
'no_info' => "На данный момент нет никакой информации",
'stats_missing_tid' => "Вы должны указать существующую тему, чтобы воспользоваться этой функцией.",
'todays_posters' => "20 авторов сегодня",
'topic_noattach' => "Тема не содержит прикрепленных файлов",
'topic_noperms' => "Вы не можете просматривать этот форум",
'top_poster_title' => "20 авторов сегодня",
'whoposted_name' => "Имя пользователя",
'whoposted_posts' => "Сообщений",
'who_farted' => "Отвечали в:",
'who_replied_title' => "Кто отвечал в эту тему",
 ); 
