<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 13 Jan 2012 04:27:33 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'gallery_loci_album' => "Просмотр альбома:",
'gallery_loci_idx' => "Просмотр главной страницы галереи",
'gallery_loci_si' => "Просмотр изображения:",
 ); 
