<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 13 Jan 2012 04:27:33 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__seo_acronyms' => "Ancronym Expansion",
'menu__seo_dashboard' => "Dashboard",
'menu__seo_dashboard1' => "Items Requiring Attention",
'menu__seo_esettings' => "Settings",
'menu__seo_keywords' => "Keywords",
'menu__seo_lastrun' => "Last Run",
'menu__seo_metatags' => "Meta Tags",
'menu__seo_rcron' => "Run via Cron",
'menu__seo_ssettings' => "Settings",
'menu__seo_visitors' => "Visitors",
 ); 
