<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 13 Jan 2012 04:27:33 +0000 by xtralv
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'gateway_desc_manual_details' => "Введите необходимую информацию для перевода вам средств.  Например, где можно распечатать чек.<br />Вы можете использовать {id} для отображения ID транзакций.",
'gateway_title_2checkout_secret_word' => "Секретное слово",
'gateway_title_2checkout_sid' => "Номер аккаунта вендора",
'gateway_title_2checkout_url' => "Checkout Type",
'gateway_title_authnet_api_login' => "API Login ID",
'gateway_title_authnet_hash' => "MD5 Hash",
'gateway_title_authnet_recurring' => "Метод для использования в периодических платежах",
'gateway_title_authnet_trans_key' => "Ключ транзакции",
'gateway_title_manual_details' => "Детали",
'gateway_title_paypalpro_api_password' => "API Password",
'gateway_title_paypalpro_api_signature' => "API Signature",
'gateway_title_paypalpro_api_username' => "API Username",
'gateway_title_paypalpro_country' => "Страна",
'gateway_title_paypalpro_recurring' => "Включить периодические платежи?",
'gateway_title_paypal_email' => "PayPal e-mail",
'gateway_title_paypal_subscriptions' => "Включить поддержку PayPal Subscriptions?",
 ); 
